USE [SindQR]
GO
/** Object:  StoredProcedure [dbo].[AJR_NUEVOINSCRIPCIONFDI]    Script Date: 11/04/2024 01:20:17 a. m. **/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[AJR_NUEVOINSCRIPCIONFDI]
  @ID_PROVEEDOR AS VARCHAR(20)=NULL,
  @FECHAOP VARCHAR(8) = NULL,
  @ID_USUARIO VARCHAR(6) = NULL,
  @TIPO VARCHAR(2)=NULLS

AS

  IF @ID_PROVEEDOR IS NULL OR  @FECHAOP IS NULL OR @ID_USUARIO IS NULL OR @TIPO IS NULL
  BEGIN
     RAISERROR('Los parámetros de entrada son incorrectos. (AJR_REGISTRAFALTASYASIS)', 16 ,1)
     RETURN
  END 

  IF NOT EXISTS (SELECT ID_PROVEEDOR FROM PROVEEDORES WHERE ID_PROVEEDOR=@ID_PROVEEDOR)
  BEGIN
     RAISERROR('El operador no se a generado con exito. (AJR_REGISTRAFALTASYASIS)', 16 ,1)
     RETURN
  END 

  DECLARE @ERROR INT,@CODIGOINSFDI VARCHAR(20),@ID_DEPTO AS VARCHAR(4),@ID_FAMILIA AS VARCHAR(4),@ID_SUBFAMILIA AS VARCHAR(4),@DESCRIPCION AS VARCHAR(120)
  
  IF @TIPO='E' 
	BEGIN
		SET @CODIGOINSFDI='25.175.1'
		SET @ID_SUBFAMILIA='2'
		SET @ID_FAMILIA='25'
		SET @ID_DEPTO='6'
		SET @DESCRIPCION='SALDO DE INSCRIPCION AL FONDO ECO: ' + @ID_PROVEEDOR
	END
  ELSE
	BEGIN
		SET @CODIGOINSFDI='26.219.1'
		SET @ID_SUBFAMILIA='1'
		SET @ID_FAMILIA='27'
		SET @ID_DEPTO='9'
		SET @DESCRIPCION='SALDO DE INSCRIPCION AL FONDO GAFETE: ' + @ID_PROVEEDOR
	END

BEGIN TRANSACTION 

	IF NOT EXISTS (SELECT ID_PROVEEDOR FROM INVENTARIO WHERE ID_PRODUCTO=@CODIGOINSFDI AND ID_PROVEEDOR=@ID_PROVEEDOR)
		BEGIN
			INSERT INTO INVENTARIO (ID_TIENDA,ID_PRODUCTO,DESCRIPCION,TIPO,ID_PROVEEDOR,ID_DEPTO,ID_SUBFAMILIA,ID_FAMILIA,ID_LOGO,CONSIGNADO,TIPOCOMISION,UNIDADENT,UNIDADSAL,
			FACTOR,EXIST,TIEMPOSURTIDO,MINIMO,MAXIMO,TASAIVA,TASAIVACOMPRA,COSTOPROMEDIO,COSTOULTIMO,TASAIMPESP,PRECIO,PRECIOCONIVA,DESCUENTO,FECHAOP,
			ID_USUARIO,COLOR,STATUS)
			SELECT '1' AS ID_TIENDA,@CODIGOINSFDI AS ID_PRODUCTO,@DESCRIPCION AS DESCRIPCION,'PRO' AS TIPO, @ID_PROVEEDOR AS ID_PROVEEDOR,@ID_DEPTO AS ID_DEPTO,
			@ID_SUBFAMILIA AS ID_SUBFAMILIA,@ID_FAMILIA AS ID_FAMILIA,'' AS LOGO,0 AS CONSIGNADO,0 AS TIPOCOMISION,'PZA' AS UNIDADENT,'PZA' AS UNIDADSAL,
			0 AS FACTOR,1 AS EXIST,0 AS TIEMPOSURTIDO,0 AS MINIMO,0 AS MAXIMO,10 AS TASAIVA,10 AS TASAIVACOMPRA,0 AS COSTOPROMEDIO,0 AS COSTOULTIMO, 0 AS TASAIMPESP,
			ROUND(90/1.1,2) AS PRECIO,90 AS PRECIOCONIVA,0 AS DESCUENTO,@FECHAOP,@ID_USUARIO AS USUARIO,'' AS COLOR,'ACTIVO' AS STATUS

			/*COBRO DE UNIFORMES UTC*/

			INSERT INTO INVENTARIO (ID_TIENDA,ID_PRODUCTO,DESCRIPCION,TIPO,ID_PROVEEDOR,ID_DEPTO,ID_SUBFAMILIA,ID_FAMILIA,ID_LOGO,CONSIGNADO,TIPOCOMISION,UNIDADENT,UNIDADSAL,
			FACTOR,EXIST,TIEMPOSURTIDO,MINIMO,MAXIMO,TASAIVA,TASAIVACOMPRA,COSTOPROMEDIO,COSTOULTIMO,TASAIMPESP,PRECIO,PRECIOCONIVA,DESCUENTO,FECHAOP,
			ID_USUARIO,COLOR,STATUS)
			SELECT '1' AS ID_TIENDA,'101.2.1' AS ID_PRODUCTO,'UTC' AS DESCRIPCION,'SER' AS TIPO, @ID_PROVEEDOR AS ID_PROVEEDOR,'2' AS ID_DEPTO,'3' AS ID_SUBFAMILIA,
			'125' AS ID_FAMILIA,'' AS LOGO,0 AS CONSIGNADO,0 AS TIPOCOMISION,'PZA' AS UNIDADENT,'PZA' AS UNIDADSAL,0 AS FACTOR,1 AS EXIST,0 AS TIEMPOSURTIDO,0 AS MINIMO,
			0 AS MAXIMO,16 AS TASAIVA,16 AS TASAIVACOMPRA,0 AS COSTOPROMEDIO,0 AS COSTOULTIMO, 0 AS TASAIMPESP,ROUND(700/1.1,2) AS PRECIO,700 AS PRECIOCONIVA,0 AS DESCUENTO,@FECHAOP,
			@ID_USUARIO AS USUARIO,'' AS COLOR,'ACTIVO' AS STATUS

			/COBRO DE EXAMEN MANEJO/

			INSERT INTO INVENTARIO (ID_TIENDA,ID_PRODUCTO,DESCRIPCION,TIPO,ID_PROVEEDOR,ID_DEPTO,ID_SUBFAMILIA,ID_FAMILIA,ID_LOGO,CONSIGNADO,TIPOCOMISION,UNIDADENT,UNIDADSAL,
			FACTOR,EXIST,TIEMPOSURTIDO,MINIMO,MAXIMO,TASAIVA,TASAIVACOMPRA,COSTOPROMEDIO,COSTOULTIMO,TASAIMPESP,PRECIO,PRECIOCONIVA,DESCUENTO,FECHAOP,
			ID_USUARIO,COLOR,STATUS)
			SELECT '1' AS ID_TIENDA,'101.2.2' AS ID_PRODUCTO,'EXAMEN DE MANEJO' AS DESCRIPCION,'SER' AS TIPO, @ID_PROVEEDOR AS ID_PROVEEDOR,'2' AS ID_DEPTO,'3' AS ID_SUBFAMILIA,
			'9' AS ID_FAMILIA,'' AS LOGO,0 AS CONSIGNADO,0 AS TIPOCOMISION,'PZA' AS UNIDADENT,'PZA' AS UNIDADSAL,0 AS FACTOR,1 AS EXIST,0 AS TIEMPOSURTIDO,0 AS MINIMO,
			0 AS MAXIMO,16 AS TASAIVA,16 AS TASAIVACOMPRA,0 AS COSTOPROMEDIO,0 AS COSTOULTIMO, 0 AS TASAIMPESP,ROUND(35/1.1,2) AS PRECIO,35 AS PRECIOCONIVA,0 AS DESCUENTO,@FECHAOP,
			@ID_USUARIO AS USUARIO,'' AS COLOR,'ACTIVO' AS STATUS

			/COBRO DE FOTO/

			INSERT INTO INVENTARIO (ID_TIENDA,ID_PRODUCTO,DESCRIPCION,TIPO,ID_PROVEEDOR,ID_DEPTO,ID_SUBFAMILIA,ID_FAMILIA,ID_LOGO,CONSIGNADO,TIPOCOMISION,UNIDADENT,UNIDADSAL,
			FACTOR,EXIST,TIEMPOSURTIDO,MINIMO,MAXIMO,TASAIVA,TASAIVACOMPRA,COSTOPROMEDIO,COSTOULTIMO,TASAIMPESP,PRECIO,PRECIOCONIVA,DESCUENTO,FECHAOP,
			ID_USUARIO,COLOR,STATUS)
			SELECT '1' AS ID_TIENDA,'101.2.3' AS ID_PRODUCTO,'FOTO' AS DESCRIPCION,'SER' AS TIPO, @ID_PROVEEDOR AS ID_PROVEEDOR,'2' AS ID_DEPTO,'3' AS ID_SUBFAMILIA,
			'8' AS ID_FAMILIA,'' AS LOGO,0 AS CONSIGNADO,0 AS TIPOCOMISION,'PZA' AS UNIDADENT,'PZA' AS UNIDADSAL,0 AS FACTOR,1 AS EXIST,0 AS TIEMPOSURTIDO,0 AS MINIMO,
			0 AS MAXIMO,16 AS TASAIVA,16 AS TASAIVACOMPRA,0 AS COSTOPROMEDIO,0 AS COSTOULTIMO, 0 AS TASAIMPESP,ROUND(75/1.1,2) AS PRECIO,75 AS PRECIOCONIVA,0 AS DESCUENTO,@FECHAOP,
			@ID_USUARIO AS USUARIO,'' AS COLOR,'ACTIVO' AS STATUS

			/COBRO DE AUTO SEGURO/

			INSERT INTO INVENTARIO (ID_TIENDA,ID_PRODUCTO,DESCRIPCION,TIPO,ID_PROVEEDOR,ID_DEPTO,ID_SUBFAMILIA,ID_FAMILIA,ID_LOGO,CONSIGNADO,TIPOCOMISION,UNIDADENT,UNIDADSAL,
			FACTOR,EXIST,TIEMPOSURTIDO,MINIMO,MAXIMO,TASAIVA,TASAIVACOMPRA,COSTOPROMEDIO,COSTOULTIMO,TASAIMPESP,PRECIO,PRECIOCONIVA,DESCUENTO,FECHAOP,
			ID_USUARIO,COLOR,STATUS)
			SELECT '1' AS ID_TIENDA,'101.2.4' AS ID_PRODUCTO,'INSCRIP. AUTOSEGURO GAMP' AS DESCRIPCION,'SER' AS TIPO, @ID_PROVEEDOR AS ID_PROVEEDOR,'2' AS ID_DEPTO,'3' AS ID_SUBFAMILIA,
			'3' AS ID_FAMILIA,'' AS LOGO,0 AS CONSIGNADO,0 AS TIPOCOMISION,'PZA' AS UNIDADENT,'PZA' AS UNIDADSAL,0 AS FACTOR,1 AS EXIST,0 AS TIEMPOSURTIDO,0 AS MINIMO,
			0 AS MAXIMO,16 AS TASAIVA,16 AS TASAIVACOMPRA,0 AS COSTOPROMEDIO,0 AS COSTOULTIMO, 0 AS TASAIMPESP,ROUND(1100/1.1,2) AS PRECIO,1100 AS PRECIOCONIVA,0 AS DESCUENTO,@FECHAOP,
			@ID_USUARIO AS USUARIO,'' AS COLOR,'ACTIVO' AS STATUS

			/COBRO DE EXAMEN SOCIOECONOMICO/

			INSERT INTO INVENTARIO (ID_TIENDA,ID_PRODUCTO,DESCRIPCION,TIPO,ID_PROVEEDOR,ID_DEPTO,ID_SUBFAMILIA,ID_FAMILIA,ID_LOGO,CONSIGNADO,TIPOCOMISION,UNIDADENT,UNIDADSAL,
			FACTOR,EXIST,TIEMPOSURTIDO,MINIMO,MAXIMO,TASAIVA,TASAIVACOMPRA,COSTOPROMEDIO,COSTOULTIMO,TASAIMPESP,PRECIO,PRECIOCONIVA,DESCUENTO,FECHAOP,
			ID_USUARIO,COLOR,STATUS)
			SELECT '1' AS ID_TIENDA,'101.2.5' AS ID_PRODUCTO,'EXAMEN SOCIOECONOMICO' AS DESCRIPCION,'SER' AS TIPO, @ID_PROVEEDOR AS ID_PROVEEDOR,'2' AS ID_DEPTO,'3' AS ID_SUBFAMILIA,
			'107' AS ID_FAMILIA,'' AS LOGO,0 AS CONSIGNADO,0 AS TIPOCOMISION,'PZA' AS UNIDADENT,'PZA' AS UNIDADSAL,0 AS FACTOR,1 AS EXIST,0 AS TIEMPOSURTIDO,0 AS MINIMO,
			0 AS MAXIMO,16 AS TASAIVA,16 AS TASAIVACOMPRA,0 AS COSTOPROMEDIO,0 AS COSTOULTIMO, 0 AS TASAIMPESP,ROUND(450/1.1,2) AS PRECIO,450 AS PRECIOCONIVA,0 AS DESCUENTO,@FECHAOP,
			@ID_USUARIO AS USUARIO,'' AS COLOR,'ACTIVO' AS STATUS

			/** INSERTAR EL COBRO DE TARJETON 

			INSERT INTO INVENTARIO (ID_TIENDA,ID_PRODUCTO,DESCRIPCION,TIPO,ID_PROVEEDOR,ID_DEPTO,ID_SUBFAMILIA,ID_FAMILIA,ID_LOGO,CONSIGNADO,TIPOCOMISION,UNIDADENT,UNIDADSAL,
			FACTOR,EXIST,TIEMPOSURTIDO,MINIMO,MAXIMO,TASAIVA,TASAIVACOMPRA,COSTOPROMEDIO,COSTOULTIMO,TASAIMPESP,PRECIO,PRECIOCONIVA,DESCUENTO,FECHAOP,
			ID_USUARIO,COLOR,STATUS)
			SELECT '1' AS ID_TIENDA,'128.1.1' AS ID_PRODUCTO,'COBRO TARJETON IDENTIDAD' AS DESCRIPCION,
			'PRO' AS TIPO, @ID_PROVEEDOR AS ID_PROVEEDOR,'23' AS ID_DEPTO,'3' AS ID_SUBFAMILIA,'128' AS ID_FAMILIA,'' AS LOGO,0 AS CONSIGNADO,
			0 AS TIPOCOMISION,'PZA' AS UNIDADENT,'PZA' AS UNIDADSAL,
			0 AS FACTOR,1 AS EXIST,0 AS TIEMPOSURTIDO,0 AS MINIMO,0 AS MAXIMO,10 AS TASAIVA,10 AS TASAIVACOMPRA,
			0 AS COSTOPROMEDIO,0 AS COSTOULTIMO, 0 AS TASAIMPESP,
			ROUND(100/1.1,2) AS PRECIO,100 AS PRECIOCONIVA,0 AS DESCUENTO,@FECHAOP,
			@ID_USUARIO AS USUARIO,'' AS COLOR,'ACTIVO' AS STATUS **/


		END

  SET @ERROR = @@ERROR
	print @ERROR
  
  IF @ERROR <> 0 
  	BEGIN
    		ROLLBACK TRANSACTION
    			IF @ERROR=1205 AND @@NESTLEVEL < 3 BEGIN
      				EXECUTE AJR_NUEVOINSCRIPCIONFDI @ID_PROVEEDOR,@FECHAOP,@ID_USUARIO,@TIPO
	      			RETURN
	 END ELSE BEGIN
      		RAISERROR('Error cargar al historico de asistencias e inscripcion al FDI. (AJR_NUEVOINSCRIPCIONFDI)', 16 ,1)    
      		RETURN
    	END
  END 

  COMMIT TRANSACTION