select 

I.Id_Producto AS PRODUCTO,
I.ID_FAMILIA AS CLAVE,
F.FAMILIA AS CARGO,
I.ID_SUBFAMILIA AS IDA,
SF.SUBFAMILIA AS A,
I.EXIST AS DEBE,
0 AS PAGA,
I.PrecioConIva as PRECIO,  
I.PrecioConIva as PRECIOFIJO, 
C.Id_Op as CONVENIO

from Inventario as I
INNER JOIN FAMILIA F ON F.ID_FAMILIA=I.ID_FAMILIA 
INNER JOIN SubFamilia SF ON SF.Id_Subfamilia = I.Id_Subfamilia
LEFT JOIN ConveniosDetalle CD ON CD.Id_Producto = I.Id_Producto
LEFT JOIN Convenios C ON C.Id_Op = CD.Id_Op
WHERE (I.ID_FAMILIA<>'36') AND (I.ID_PROVEEDOR='8624' AND I.EXIST > 0) OR (I.ID_PROVEEDOR='OP-38217' AND I.EXIST > 0  AND I.ID_FAMILIA NOT IN ('11'))