SELECT I.ID_FAMILIA AS CLAVE,F.FAMILIA AS CARGO,I.ID_SUBFAMILIA AS IDA, S.SUBFAMILIA AS A, SUM(I.EXIST)AS DEBE, 0 AS PAGA, I.PrecioConIva as PRECIO
FROM INVENTARIO I 
INNER JOIN FAMILIA F ON F.ID_FAMILIA=I.ID_FAMILIA 
INNER JOIN SUBFAMILIA S ON S.ID_SUBFAMILIA=I.ID_SUBFAMILIA 
WHERE (I.ID_FAMILIA<>'36') AND (I.ID_PROVEEDOR='859' AND I.EXIST > 0) OR (I.ID_PROVEEDOR='OP-38211' AND I.EXIST >0  AND I.ID_FAMILIA NOT IN ('0','11')) 
GROUP BY I.ID_FAMILIA,F.FAMILIA,I.ID_SUBFAMILIA,S.SUBFAMILIA, I.PrecioConIva
ORDER BY I.ID_SUBFAMILIA,I.ID_FAMILIA