<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0-windows10.0.19041.0</TargetFrameworks>
		
		<!-- INICIO DE SOLUCION -->
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PlatformTarget>x64</PlatformTarget>
		<!-- FIN DE SOLUCION -->
		
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net8.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>Cajas</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>Cajas</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.tippingpoint.cajas</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<GenerateAppInstallerFile>False</GenerateAppInstallerFile>
		<AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
		<AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
		<AppxAutoIncrementPackageRevision>True</AppxAutoIncrementPackageRevision>
		<AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
		<GenerateTestArtifacts>True</GenerateTestArtifacts>
		<HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
		<PackageCertificateThumbprint>AD9CB3DF428C042BAF450E815CC473E58F5CD5A5</PackageCertificateThumbprint>
    <UseSystemDrawing>true</UseSystemDrawing>


		<!-- Empaquetado Windows MSIX -->
		<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
		<SelfContained>true</SelfContained>
		<WindowsPackageType>MSIX</WindowsPackageType>
		<GenerateAppxPackageOnBuild>true</GenerateAppxPackageOnBuild>

		<Platforms>AnyCPU;x64</Platforms>

    
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-maccatalyst|AnyCPU'">
	  <ApplicationTitle>Practicontrol 2025</ApplicationTitle>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-maccatalyst|x64'">
	  <ApplicationTitle>Practicontrol 2025</ApplicationTitle>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-windows10.0.19041.0|AnyCPU'">
	  <ApplicationTitle>Practicontrol 2025</ApplicationTitle>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-windows10.0.19041.0|x64'">
	  <ApplicationTitle>Practicontrol 2025</ApplicationTitle>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-maccatalyst|AnyCPU'">
	  <ApplicationTitle>Practicontrol 2025</ApplicationTitle>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-maccatalyst|x64'">
	  <ApplicationTitle>Practicontrol 2025</ApplicationTitle>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-windows10.0.19041.0|AnyCPU'">
	  <ApplicationTitle>Practicontrol 2025</ApplicationTitle>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-windows10.0.19041.0|x64'">
	  <ApplicationTitle>Practicontrol 2025</ApplicationTitle>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="MVVM\Pages\log\**" />
	  <Compile Remove="Services\Services\**" />
	  <EmbeddedResource Remove="MVVM\Pages\log\**" />
	  <EmbeddedResource Remove="Services\Services\**" />
	  <MauiCss Remove="MVVM\Pages\log\**" />
	  <MauiCss Remove="Services\Services\**" />
	  <MauiXaml Remove="MVVM\Pages\log\**" />
	  <MauiXaml Remove="Services\Services\**" />
	  <None Remove="MVVM\Pages\log\**" />
	  <None Remove="Services\Services\**" />
	</ItemGroup>

	<ItemGroup>
	  <MauiImage Remove="Resources\Images\dotnet_bot.png" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Resources\Images\dotnet_bot.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AWSSDK.Core" Version="4.0.0.3" />
		<PackageReference Include="AWSSDK.S3" Version="4.0.0.3" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="EntityFramework" Version="6.4.4" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.1" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.100" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.100" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Openpay" Version="1.0.27" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.9.0" />
		<PackageReference Include="ZXing.Net.Maui" Version="0.4.0" />
		<PackageReference Include="ZXing.Net.Maui.Controls" Version="0.4.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\radiotaxi.Model\radiotaxi.Model.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Platforms\Windows\Utils\" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="MVVM\Pages\AppShell.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Pages\blocks\Blocks.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Pages\Cards\Card.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Pages\cars\Car.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Pages\cars\CarNotFound.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Pages\contact\chat.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Pages\contact\info.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Pages\contact\revist.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Pages\convs\Convs.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Pages\cupones\CuponesView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Pages\debs\Debs.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Pages\Home.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Pages\LoginPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Pages\OnboardingPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="MVVM\Pages\scan\Scan.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\AppStyles.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

	<ItemGroup>
	  <PRIResource Remove="MVVM\Pages\log\**" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="MVVM\Pages\cupones\CuponesFINAL.xaml.cs" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Remove="MVVM\Pages\cupones\CuponesFINAL.xaml" />
	</ItemGroup>

	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
		<PackageReference Include="System.Drawing.Common" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <PRIResource Remove="Services\Services\**" />
	</ItemGroup>

	<ItemGroup>
	  <EditorConfigFiles Remove="C:\Users\fdoag\Documents\Developer\Proyectos\practicontrol\Cajas\Services\.editorconfig" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="C:\Users\fdoag\Documents\Developer\Proyectos\practicontrol\Cajas\Services\.editorconfig" />
	</ItemGroup>

</Project>
