USE [SindQR]
GO
/****** Object:  StoredProcedure [dbo].[AJR_REGISTRAASISTENCIA]    Script Date: 27/02/2025 01:20:55 a. m. ******/
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[AJR_REGISTRAASISTENCIA]
  @GAFETE VARCHAR(20)=NULL, 
  @TIPO VARCHAR(2)=NULL, 
  @TAXI VARCHAR(10)=NULL,
  @TURNO VARCHAR(1) = NULL,
  @FECHAREPORTE DATETIME= NULL, 
  @CONCEPTO VARCHAR(4)= NULL, 
  @TICKET VARCHAR(15)= NULL,
  @FECHAOP DATETIME= NULL, 
  @USARVARINICIO BIT=0,
  @FECHAVARINICIO DATETIME= NULL
AS
  
  IF @GAFETE IS NULL OR @TIPO IS NULL OR @TAXI IS NULL OR @TURNO IS NULL OR @FECHAREPORTE IS NULL OR @CONCEPTO IS NULL OR 
     @TICKET IS NULL OR  @FECHAOP IS NULL OR @FECHAVARINICIO IS NULL
  BEGIN
     RAISERROR('Error al registrar la Asistencia. Los parámetros de entrada son incorrectos. (AJR_REGISTRAASISTENCIA)', 16 ,1)
     RETURN
  END 

DECLARE @ERROR INT
DECLARE @ULTFECHARESPTEXT AS VARCHAR(11),@FECHAASIS DATETIME

	IF @USARVARINICIO=1
		BEGIN
			SET @FECHAASIS=@FECHAVARINICIO
		END
	ELSE
		BEGIN
			SET @ULTFECHARESPTEXT=ISNULL((select CONVERT(VARchar(11), MAX(FECHAREPORTE)) from HISTASISTENCIAS WHERE GAFETE=@GAFETE),CONVERT(VARchar(11), GETDATE()))
			SET @FECHAASIS=@ULTFECHARESPTEXT
			SET @FECHAASIS=@FECHAASIS+1
		END

  BEGIN TRANSACTION 
	
	IF @TURNO = 'D'
		BEGIN
			INSERT INTO HISTASISTENCIAS (GAFETE, TIPO, TAXI, TURNO, FECHAREPORTE, CONCEPTO, TICKET,FECHAOP)
			VALUES (@GAFETE, @TIPO, @TAXI, 'M', @FECHAASIS, @CONCEPTO, @TICKET,@FECHAOP)
	
			INSERT INTO HISTASISTENCIAS (GAFETE, TIPO, TAXI, TURNO, FECHAREPORTE, CONCEPTO, TICKET,FECHAOP)
			VALUES (@GAFETE, @TIPO, @TAXI, 'V', @FECHAASIS, @CONCEPTO, @TICKET,@FECHAOP)
		END
	ELSE
		BEGIN
			INSERT INTO HISTASISTENCIAS (GAFETE, TIPO, TAXI, TURNO, FECHAREPORTE, CONCEPTO, TICKET,FECHAOP)
			VALUES (@GAFETE, @TIPO, @TAXI, @TURNO, @FECHAASIS, @CONCEPTO, @TICKET,@FECHAOP)
		END

  SET @ERROR = @@ERROR

  IF @ERROR <> 0 
  BEGIN
    ROLLBACK TRANSACTION
    IF @ERROR=1205 AND @@NESTLEVEL < 3 BEGIN
      EXECUTE AJR_REGISTRAASISTENCIA @GAFETE, @TIPO, @TAXI, @TURNO, @FECHAREPORTE, @CONCEPTO, @TICKET
      RETURN
    END ELSE BEGIN
      RAISERROR('Error al registrar la Asistencia. (AJR_REGISTRAASISTENCIA)', 16 ,1)    
      RETURN
    END
  END 

  COMMIT TRANSACTION