//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class radiotaxiEntities : DbContext
    {
        public radiotaxiEntities()
            : base("name=radiotaxiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Group> C_Group { get; set; }
        public virtual DbSet<C_Group_user> C_Group_user { get; set; }
        public virtual DbSet<AppService> AppServices { get; set; }
        public virtual DbSet<baseService> baseServices { get; set; }
        public virtual DbSet<catalogService> catalogServices { get; set; }
        public virtual DbSet<ChatMessage> ChatMessages { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<GPSphone> GPSphones { get; set; }
        public virtual DbSet<package> packages { get; set; }
        public virtual DbSet<paymentPackage> paymentPackages { get; set; }
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<rtNumberService> rtNumberServices { get; set; }
        public virtual DbSet<statusService> statusServices { get; set; }
        public virtual DbSet<taxiApp> taxiApps { get; set; }
        public virtual DbSet<taxiReport> taxiReports { get; set; }
        public virtual DbSet<taxiService> taxiServices { get; set; }
        public virtual DbSet<unit_taxi> unit_taxi { get; set; }
        public virtual DbSet<audience> audiences { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<firebase> firebases { get; set; }
        public virtual DbSet<parameter> parameters { get; set; }
        public virtual DbSet<profile> profiles { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<roleparam> roleparams { get; set; }
        public virtual DbSet<token> tokens { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userBiometricData> userBiometricDatas { get; set; }
        public virtual DbSet<userCompany> userCompanies { get; set; }
        public virtual DbSet<userDepartment> userDepartments { get; set; }
        public virtual DbSet<userProfile> userProfiles { get; set; }
        public virtual DbSet<userRole> userRoles { get; set; }
        public virtual DbSet<userSession> userSessions { get; set; }
        public virtual DbSet<C_Group1> C_Group1 { get; set; }
        public virtual DbSet<C_Group_user1> C_Group_user1 { get; set; }
        public virtual DbSet<AppService1> AppService1 { get; set; }
        public virtual DbSet<baseService1> baseService1 { get; set; }
        public virtual DbSet<catalogService1> catalogService1 { get; set; }
        public virtual DbSet<ChatMessage1> ChatMessage1 { get; set; }
        public virtual DbSet<client1> client1 { get; set; }
        public virtual DbSet<GPSphone1> GPSphone1 { get; set; }
        public virtual DbSet<package1> package1 { get; set; }
        public virtual DbSet<paymentPackage1> paymentPackage1 { get; set; }
        public virtual DbSet<report1> report1 { get; set; }
        public virtual DbSet<rtNumberService1> rtNumberService1 { get; set; }
        public virtual DbSet<statusService1> statusService1 { get; set; }
        public virtual DbSet<taxiApp1> taxiApp1 { get; set; }
        public virtual DbSet<taxiReport1> taxiReport1 { get; set; }
        public virtual DbSet<taxiService1> taxiService1 { get; set; }
        public virtual DbSet<unit_taxi1> unit_taxi1 { get; set; }
        public virtual DbSet<InterestPoint> InterestPoints { get; set; }
        public virtual DbSet<PointType> PointTypes { get; set; }
        public virtual DbSet<Rate> Rates { get; set; }
        public virtual DbSet<SuperBlock> SuperBlocks { get; set; }
        public virtual DbSet<Tariff> Tariffs { get; set; }
        public virtual DbSet<Zone> Zones { get; set; }
    }
}
