//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class accident
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public accident()
        {
            this.documents = new HashSet<document>();
            this.PanicAlerts = new HashSet<PanicAlert>();
        }
    
        public int id { get; set; }
        public System.DateTime datecreate { get; set; }
        public System.DateTime dateaccident { get; set; }
        public int graficdate { get; set; }
        public string sm { get; set; }
        public string place { get; set; }
        public string zone { get; set; }
        public string ecoplate { get; set; }
        public string percentage { get; set; }
        public string partnername { get; set; }
        public string platessystem { get; set; }
        public string otherplates { get; set; }
        public string ecopatnerresponsable { get; set; }
        public string patnerresponsable { get; set; }
        public string responsiblepartner { get; set; }
        public string nameoperator { get; set; }
        public string badgeoperator { get; set; }
        public string percentageoperator { get; set; }
        public string numberfaultsoperator { get; set; }
        public string ageoperator { get; set; }
        public string antiquityoperator { get; set; }
        public string licenseoperator { get; set; }
        public System.DateTime expirationlicense { get; set; }
        public string capturist { get; set; }
        public string injured { get; set; }
        public string numberpolicy { get; set; }
        public string numbersinister { get; set; }
        public Nullable<bool> observationsfordelegate { get; set; }
        public string documentsannexed { get; set; }
        public string damagetaxi { get; set; }
        public string damageanothervehicle { get; set; }
        public string otherdamages { get; set; }
        public string specify { get; set; }
        public string accidentdetail { get; set; }
        public string observationbyoperator { get; set; }
        public string taxireportobservation { get; set; }
        public Nullable<bool> serviceorder { get; set; }
        public Nullable<bool> preliminaryinquiry { get; set; }
        public Nullable<bool> criminalcause { get; set; }
        public int id_alcohol { get; set; }
        public int id_involved { get; set; }
        public int id_causeaccident { get; set; }
        public int id_typeaccident { get; set; }
        public int id_manageroperational { get; set; }
        public int id_policysecure { get; set; }
        public int id_insurance { get; set; }
        public int id_adjuster { get; set; }
        public int id_delegateoperational { get; set; }
        public int id_autoinsurance { get; set; }
        public int id_delegateintransit { get; set; }
        public int id_responsibleintransit { get; set; }
        public int id_managerinmp { get; set; }
        public int id_responsibleinmp { get; set; }
        public int id_licincourt { get; set; }
        public int id_responsibleincourt { get; set; }
        public int id_hospital { get; set; }
        public int id_garage { get; set; }
        public int id_confinement { get; set; }
        public int id_cranes { get; set; }
        public int id_responsable { get; set; }
        public int id_status_accident { get; set; }
        public int id_user { get; set; }
        public string timeaccident { get; set; }
        public string other_taxis { get; set; }
        public string Unknown_driver_name { get; set; }
    
        public virtual adjuster adjuster { get; set; }
        public virtual alcohol alcohol { get; set; }
        public virtual autoinsurance autoinsurance { get; set; }
        public virtual causeaccident causeaccident { get; set; }
        public virtual confinement confinement { get; set; }
        public virtual crane crane { get; set; }
        public virtual delegateoperational delegateoperational { get; set; }
        public virtual delegateintransit delegateintransit { get; set; }
        public virtual garage garage { get; set; }
        public virtual hospital hospital { get; set; }
        public virtual involved involved { get; set; }
        public virtual insurance insurance { get; set; }
        public virtual licincourt licincourt { get; set; }
        public virtual manageroperational manageroperational { get; set; }
        public virtual managerinmp managerinmp { get; set; }
        public virtual policysecure policysecure { get; set; }
        public virtual responsibleintransit responsibleintransit { get; set; }
        public virtual responsibleinmp responsibleinmp { get; set; }
        public virtual responsibleincourt responsibleincourt { get; set; }
        public virtual responsable responsable { get; set; }
        public virtual status_accidents status_accidents { get; set; }
        public virtual typeaccident typeaccident { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<document> documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PanicAlert> PanicAlerts { get; set; }
    }
}
