//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actas_Convenios
    {
        public short EconRenta { get; set; }
        public string Daenrenta { get; set; }
        public short EconTomaRenta { get; set; }
        public string Tomaenrenta { get; set; }
        public string Duracion { get; set; }
        public System.DateTime Inicio { get; set; }
        public System.DateTime Fin { get; set; }
        public Nullable<decimal> Pago { get; set; }
        public string PagoLetra { get; set; }
        public string Titularactas { get; set; }
        public string RentClau1 { get; set; }
        public string RentClau2 { get; set; }
        public string RentClau3 { get; set; }
        public string RentClau4 { get; set; }
        public string Clausula1 { get; set; }
        public string Clausula2 { get; set; }
        public string Clausula3 { get; set; }
        public string Clausula4 { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> FechaOp { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> FechaEdit { get; set; }
        public string UsuarioEdit { get; set; }
        public string EcoTrasferido { get; set; }
        public string NombreTransferido { get; set; }
        public Nullable<decimal> PagoTransf { get; set; }
        public string PagoLetraTransf { get; set; }
        public string FechaTransferido { get; set; }
        public string ID_OP { get; set; }
        public string EsRentador { get; set; }
    }
}
