//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class address_sectors
    {
        public int id { get; set; }
        public string name { get; set; }
        public int id_zone { get; set; }
        public int id_address { get; set; }
    
        public virtual userAddress userAddress { get; set; }
        public virtual sector sector { get; set; }
    }
}
