//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class asistenciaTemporal
    {
        public int idempleado { get; set; }
        public string claveempleado { get; set; }
        public string nombre { get; set; }
        public System.DateTime checktime { get; set; }
        public string tipo { get; set; }
        public System.DateTime fecha { get; set; }
        public string status { get; set; }
    }
}
