//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignment
    {
        public int id { get; set; }
        public int perfilId { get; set; }
        public int userId { get; set; }
        public string createdBy { get; set; }
        public System.DateTime createdDate { get; set; }
        public string editedBy { get; set; }
        public System.DateTime editedDate { get; set; }
        public System.DateTime dateassignment { get; set; }
        public string note { get; set; }
        public string comments { get; set; }
        public bool visit { get; set; }
        public int statusAssignmentId { get; set; }
        public bool mobilization { get; set; }
        public bool mobilizer { get; set; }
        public bool turn { get; set; }
        public Nullable<System.DateTime> dateVisit { get; set; }
        public string activist { get; set; }
        public string atend { get; set; }
        public string socialNetwork { get; set; }
        public string phoneCel { get; set; }
        public string phoneHouse { get; set; }
        public Nullable<int> tend { get; set; }
        public string mhours { get; set; }
        public Nullable<int> round { get; set; }
        public int activistId { get; set; }
        public int tendCatalog { get; set; }
        public string observations { get; set; }
        public string phone { get; set; }
        public Nullable<int> id_address { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
    
        public virtual activist activist1 { get; set; }
        public virtual userAddress userAddress { get; set; }
        public virtual statusAssignment statusAssignment { get; set; }
        public virtual user user { get; set; }
    }
}
