//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUT_RECALCULOCONV
    {
        public string ID_OP { get; set; }
        public string CONCEPTO { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public string STATUS { get; set; }
        public string REFAUTOSEG { get; set; }
        public Nullable<decimal> NOTAS { get; set; }
        public string CARGOANUM { get; set; }
        public int CONSCONTROL { get; set; }
        public Nullable<decimal> PAGOSAZUL { get; set; }
    }
}
