//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public System.DateTime FECHA { get; set; }
        public string Id_usuario { get; set; }
        public string USUARIO { get; set; }
        public System.DateTime HORA { get; set; }
        public string CLASE { get; set; }
        public string UBICACION { get; set; }
        public bool PC { get; set; }
    }
}
