//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraAplicacione
    {
        public int id_op { get; set; }
        public string Accion { get; set; }
        public string procedimiento { get; set; }
        public string Parametros { get; set; }
        public System.DateTime FechaSistema { get; set; }
        public System.DateTime FechaServidor { get; set; }
        public string id_usuario { get; set; }
        public string computadora { get; set; }
        public Nullable<System.DateTime> horaMaquina { get; set; }
    }
}
