//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boletine
    {
        public Nullable<int> Taxi { get; set; }
        public string Motivo { get; set; }
        public string Ordeno { get; set; }
        public Nullable<System.DateTime> Fechaboletin { get; set; }
        public Nullable<System.DateTime> Horaboletin { get; set; }
        public string UsuarioAlta { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> FechaAseg { get; set; }
        public Nullable<System.DateTime> HoraAsegu { get; set; }
        public string usuarioRegAsegu { get; set; }
        public Nullable<System.DateTime> FechaLiberado { get; set; }
        public Nullable<System.DateTime> HoraLibera { get; set; }
        public string obs_liberacion { get; set; }
        public string UsuarioLibera { get; set; }
        public int Control { get; set; }
    }
}
