//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_permissions
    {
        public int id { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> dateEdited { get; set; }
        public string EditedBy { get; set; }
        public string id_Operacion { get; set; }
        public Nullable<System.DateTime> dateStart { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public int id_user { get; set; }
        public string gafet { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<System.DateTime> dateDisabled { get; set; }
        public string DisableBy { get; set; }
        public Nullable<decimal> control { get; set; }
        public string taxi { get; set; }
        public Nullable<System.DateTime> datePrinted { get; set; }
        public string PrintedByUser { get; set; }
        public string PrintedBy { get; set; }
        public string authorizedBy { get; set; }
        public string authorizeDate { get; set; }
        public bool authorize { get; set; }
    
        public virtual user user { get; set; }
    }
}
