//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public card()
        {
            this.cardsPrinteds = new HashSet<cardsPrinted>();
        }
    
        public int id { get; set; }
        public int userId { get; set; }
        public string partnerReference { get; set; }
        public string taxi { get; set; }
        public Nullable<System.DateTime> asignedDate { get; set; }
        public string asgnedBy { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> lastEditedDate { get; set; }
        public string editedBy { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> turn { get; set; }
        public Nullable<bool> deliver { get; set; }
        public Nullable<System.DateTime> deliverDate { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public Nullable<double> id_Op { get; set; }
        public Nullable<bool> low { get; set; }
        public Nullable<System.DateTime> lowDate { get; set; }
    
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cardsPrinted> cardsPrinteds { get; set; }
    }
}
