//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carge
    {
        public int id { get; set; }
        public decimal amount { get; set; }
        public decimal authorization { get; set; }
        public string method { get; set; }
        public string operation_type { get; set; }
        public string transaction_type { get; set; }
        public string status { get; set; }
        public string currency { get; set; }
        public System.DateTime creation_date { get; set; }
        public System.DateTime operation_date { get; set; }
        public string description { get; set; }
        public string order_id { get; set; }
    }
}
