//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CederAutorizacion
    {
        public int Id { get; set; }
        public Nullable<short> Numero { get; set; }
        public bool Fiscal { get; set; }
        public bool Actas { get; set; }
        public bool Sistema { get; set; }
        public string Observaciones { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Fch_Op { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Fch_Edit { get; set; }
        public string UsuarioEdi { get; set; }
    }
}
