//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargesItem
    {
        public int id { get; set; }
        public string PRODUCTO { get; set; }
        public string TYPE { get; set; }
        public string CLAVE { get; set; }
        public string CARGO { get; set; }
        public string IDA { get; set; }
        public string A { get; set; }
        public int DEBE { get; set; }
        public int PAGA { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<decimal> PRECIOFIJO { get; set; }
        public string Id_Producto { get; set; }
        public System.DateTime FechaOp { get; set; }
        public string Descripcion { get; set; }
        public string CONVENIO { get; set; }
        public string RTYPE { get; set; }
        public bool RDOUBLE { get; set; }
        public int MULTIPLICADOR { get; set; }
        public Nullable<int> charges_id { get; set; }
    
        public virtual Charge Charge { get; set; }
    }
}
