//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class chof_exp
    {
        public string CHOFER { get; set; }
        public string ECONOMICO { get; set; }
        public Nullable<System.DateTime> FECHAINI { get; set; }
        public Nullable<System.DateTime> FECHAFIN { get; set; }
        public Nullable<short> CONCEPTO { get; set; }
        public string COMENTARIO { get; set; }
        public string SWASISTEN { get; set; }
        public Nullable<short> NDIAS { get; set; }
        public Nullable<double> TAXI { get; set; }
        public string TURNO { get; set; }
        public Nullable<bool> ACTUALIZ { get; set; }
        public Nullable<double> NDIASREG { get; set; }
        public string ConceptoD { get; set; }
        public Nullable<System.DateTime> FechaOp { get; set; }
        public string Usuario { get; set; }
        public int Id_op { get; set; }
        public string Acciontomada { get; set; }
    }
}
