//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chof_Head
    {
        public string CHOFER { get; set; }
        public string ESTATUS { get; set; }
        public string ULTTAXI { get; set; }
        public string ULTTURNO { get; set; }
        public Nullable<System.DateTime> ULTASIS { get; set; }
        public Nullable<double> DIASASIS { get; set; }
        public Nullable<double> FALTAS { get; set; }
        public Nullable<double> PASIS { get; set; }
        public Nullable<double> DIASASIS2 { get; set; }
        public Nullable<double> FALTAS2 { get; set; }
        public Nullable<double> PASIS2 { get; set; }
        public Nullable<double> CALCASIS { get; set; }
        public Nullable<bool> REN_FONDO { get; set; }
        public Nullable<double> FIANZA { get; set; }
        public string MAYACARIBE { get; set; }
        public Nullable<System.DateTime> FCALCASIS { get; set; }
        public Nullable<decimal> SALDOIDEF { get; set; }
        public Nullable<decimal> SALDOCDEF { get; set; }
        public Nullable<decimal> SALDOFZA { get; set; }
        public Nullable<decimal> SALDOINSC { get; set; }
        public Nullable<System.DateTime> FECHAEDIT { get; set; }
        public string USUARIOEDIT { get; set; }
    }
}
