//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chof_datbaja
    {
        public string CHOFER { get; set; }
        public Nullable<System.DateTime> FECHABAJ { get; set; }
        public string MOTIVOBAJA { get; set; }
        public string OBSERVAC { get; set; }
        public string SOLICBAJA { get; set; }
        public Nullable<bool> RETIROFZA { get; set; }
        public Nullable<System.DateTime> FECHARETFZA { get; set; }
        public string CHEQUE { get; set; }
        public Nullable<decimal> IMPORTE_OP { get; set; }
        public string CHEQUE2 { get; set; }
        public Nullable<decimal> IMPORSOCIO { get; set; }
        public string CHEQUE3 { get; set; }
        public Nullable<decimal> IMPORDEUDA { get; set; }
        public Nullable<System.DateTime> FECHAREACTIVA { get; set; }
        public string AUTORIZA { get; set; }
        public string OBS_REACTIVA { get; set; }
        public Nullable<System.DateTime> FECHAOP { get; set; }
        public string ID_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHAEDIT { get; set; }
        public string ID_USUARIOEDIT { get; set; }
    }
}
