//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chof_FondoHead
    {
        public string Numero { get; set; }
        public string Poliza { get; set; }
        public Nullable<System.DateTime> InicioVigencia { get; set; }
        public string Plazo { get; set; }
        public string FrecuenciaPago { get; set; }
        public string Aplicacion { get; set; }
        public string OpcionIncremento { get; set; }
        public Nullable<decimal> P_Basica { get; set; }
        public Nullable<decimal> P_Complementaria { get; set; }
        public Nullable<decimal> Primatotal { get; set; }
        public Nullable<decimal> Cobertura { get; set; }
        public string CoberturaLetra { get; set; }
        public Nullable<bool> ActaNacimiento { get; set; }
        public Nullable<bool> Identificacion { get; set; }
        public Nullable<bool> Otro { get; set; }
        public string Obs { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string TitularFondo { get; set; }
        public string SecretarioGeneral { get; set; }
    }
}
