//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Christmasgift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Christmasgift()
        {
            this.ChristmasgiftPrinteds = new HashSet<ChristmasgiftPrinted>();
        }
    
        public long id { get; set; }
        public string membership_type { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryBy { get; set; }
        public Nullable<int> userid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChristmasgiftPrinted> ChristmasgiftPrinteds { get; set; }
        public virtual user user { get; set; }
    }
}
