//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChristmasgiftPrinted
    {
        public long id { get; set; }
        public string membership_type { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> PrintedDate { get; set; }
        public string PrintedBy { get; set; }
        public Nullable<long> Christmasgiftid { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual Christmasgift Christmasgift { get; set; }
    }
}
