//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public string Id_Cliente { get; set; }
        public string Id_Tienda { get; set; }
        public string Cliente1 { get; set; }
        public string Direccion { get; set; }
        public string RFC { get; set; }
        public string Ciudad { get; set; }
        public string Telefono { get; set; }
        public string RefCobranza { get; set; }
        public string Id_Vendedor { get; set; }
        public Nullable<decimal> Credito { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<int> DiasCred { get; set; }
        public Nullable<System.DateTime> UltimaComp { get; set; }
        public Nullable<decimal> VentasAnuales { get; set; }
        public Nullable<System.DateTime> FechaOp { get; set; }
        public Nullable<System.DateTime> FechaEdit { get; set; }
        public string Id_Usuario { get; set; }
    }
}
