//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public string Id_Op { get; set; }
        public string Id_Tienda { get; set; }
        public decimal Rate { get; set; }
        public string Id_Proveedor { get; set; }
        public string Referencia { get; set; }
        public string No_Doc { get; set; }
        public string Concepto { get; set; }
        public string Status { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public System.DateTime FechaRecepcion { get; set; }
        public string Condicion { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public decimal Importe { get; set; }
        public decimal Desporcen { get; set; }
        public decimal DescImp { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Iva { get; set; }
        public bool DesgloceIva { get; set; }
        public decimal Total { get; set; }
        public bool Indirectos { get; set; }
        public decimal IndirecosImp { get; set; }
        public string Id_Usuario { get; set; }
        public System.DateTime FechaOp { get; set; }
        public System.DateTime FechaEdit { get; set; }
        public string Id_UsuarioEdit { get; set; }
    }
}
