//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprasDetalle
    {
        public string Id_Op { get; set; }
        public decimal Cant { get; set; }
        public string Id_Producto { get; set; }
        public string Id_Proveedor { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio_Lista { get; set; }
        public decimal Descporc { get; set; }
        public decimal Descimp { get; set; }
        public decimal Precio { get; set; }
        public decimal Importe { get; set; }
        public decimal PorcIva { get; set; }
        public decimal Iva { get; set; }
        public decimal Indirecto { get; set; }
        public decimal CostoNeto { get; set; }
        public decimal CostoPromedio { get; set; }
        public decimal Devueltos { get; set; }
    }
}
