//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptosConveniosRelacion
    {
        public string Id_ConceptoConv { get; set; }
        public string Id_Depto { get; set; }
        public string Id_Familia { get; set; }
        public string Id_Subfamilia { get; set; }
        public string Id_Secretaria { get; set; }
    
        public virtual ConceptosConvenio ConceptosConvenio { get; set; }
    }
}
