//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Control
    {
        public string Empresa { get; set; }
        public string Direccion { get; set; }
        public string RFC { get; set; }
        public string Telefono { get; set; }
        public string PathDatos { get; set; }
        public string PathReportes { get; set; }
        public string PathSys { get; set; }
        public string PasswordDatos { get; set; }
        public string PasswordSys { get; set; }
        public string NoSerie { get; set; }
        public System.DateTime FechaSys { get; set; }
    }
}
