//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlObligacione
    {
        public Nullable<int> Numero { get; set; }
        public Nullable<int> Id_obligacion { get; set; }
        public string Obligacion { get; set; }
        public string Periodo { get; set; }
        public Nullable<short> Año { get; set; }
        public Nullable<bool> Cubierto { get; set; }
        public Nullable<System.DateTime> Vence { get; set; }
        public Nullable<System.DateTime> Fch_Pago { get; set; }
        public string Ticket { get; set; }
        public Nullable<double> NumDep { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> Recargos { get; set; }
        public Nullable<decimal> Actualizacion { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> Fch_Cargo { get; set; }
        public string FolioCargo { get; set; }
        public Nullable<decimal> MontoInf { get; set; }
        public Nullable<System.DateTime> Fch_Op { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Fch_edit { get; set; }
        public string UsuarioEdit { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> Bimestre { get; set; }
        public bool Pago_contabilidad { get; set; }
        public Nullable<System.DateTime> Fecha_pago_contabilidad { get; set; }
        public string ticket_pago_contabilidad { get; set; }
        public Nullable<decimal> importe_pago_Contabilidad { get; set; }
        public bool Pago_conta_declaracion { get; set; }
        public Nullable<System.DateTime> Fecha_pago_conta_declaracion { get; set; }
        public Nullable<decimal> importe_pago_conta_declaracion { get; set; }
        public string ticket_pago_conta_declaracion { get; set; }
    }
}
