//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConvenioFactura
    {
        public string Id_Op { get; set; }
        public string Factura { get; set; }
        public string Folio { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public decimal Cantidad { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public decimal Importe { get; set; }
        public decimal ConsecNoError { get; set; }
    }
}
