//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConveniosDetalle
    {
        public string Id_Op { get; set; }
        public int Folio { get; set; }
        public string Id_Producto { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<System.DateTime> Vence { get; set; }
        public string Status { get; set; }
        public string Id_Pago { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string Id_PagoSoc { get; set; }
        public Nullable<System.DateTime> FechaPS { get; set; }
        public string Id_UsuarioPago { get; set; }
        public string Id_UsuarioPS { get; set; }
        public bool StatusInv { get; set; }
    }
}
