//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Convenio
    {
        public string Id_Op { get; set; }
        public string Id_Secretaria { get; set; }
        public string Secretaria { get; set; }
        public string Id_Usuario { get; set; }
        public string Usuario { get; set; }
        public string Id_Concepto { get; set; }
        public string Concepto { get; set; }
        public Nullable<int> CargoA { get; set; }
        public string CargoANum { get; set; }
        public string CargoANombre { get; set; }
        public string AfavordeNum { get; set; }
        public string AfavordeNombre { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> Partidas { get; set; }
        public Nullable<decimal> Plazo { get; set; }
        public Nullable<System.DateTime> PrimerVencimiento { get; set; }
        public Nullable<decimal> ImportePago { get; set; }
        public Nullable<System.DateTime> FechaOp { get; set; }
        public Nullable<System.DateTime> HoraOp { get; set; }
        public Nullable<System.DateTime> FechaEdit { get; set; }
        public string Id_UsuarioEdit { get; set; }
        public string Status { get; set; }
        public string Observaciones { get; set; }
        public string TotalLetras { get; set; }
        public string REFAUTOSEG { get; set; }
        public Nullable<decimal> PAGOSaZUL { get; set; }
        public Nullable<decimal> FACTURASCARG { get; set; }
    }
}
