//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class coordinate
    {
        public int id { get; set; }
        public string lat { get; set; }
        public string @long { get; set; }
        public Nullable<int> gps_id { get; set; }
        public System.DateTime dateCreated { get; set; }
    
        public virtual gp gp { get; set; }
    }
}
