//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CouponPayment()
        {
            this.CouponPaymentDetails = new HashSet<CouponPaymentDetail>();
            this.Cupons = new HashSet<Cupon>();
        }
    
        public int CouponPaymentId { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<int> userId { get; set; }
        public byte PaymentMethod { get; set; }
        public string Reference { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Active { get; set; }
        public bool Cancelled { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public Nullable<int> CancelledBy { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponPaymentDetail> CouponPaymentDetails { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cupon> Cupons { get; set; }
    }
}
