//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class creditcard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public creditcard()
        {
            this.transactions = new HashSet<transaction>();
        }
    
        public int id { get; set; }
        public int userId { get; set; }
        public string Ultimos4 { get; set; }
        public string token { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<bool> active { get; set; }
        public string type { get; set; }
        public string brand { get; set; }
        public string card_number { get; set; }
        public string bank_name { get; set; }
        public string customer_id { get; set; }
    
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction> transactions { get; set; }
    }
}
