//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cupon()
        {
            this.CouponPaymentDetails = new HashSet<CouponPaymentDetail>();
        }
    
        public int CuponsID { get; set; }
        public string Name { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string EditedBy { get; set; }
        public System.DateTime EditedDate { get; set; }
        public bool active { get; set; }
        public bool @lock { get; set; }
        public Nullable<int> UserID { get; set; }
        public int CouponratesID { get; set; }
        public Nullable<int> cuponsGroupPrintedId { get; set; }
        public Nullable<int> CouponPaymentId { get; set; }
        public bool Paid { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> serial_ex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponPaymentDetail> CouponPaymentDetails { get; set; }
        public virtual CouponPayment CouponPayment { get; set; }
        public virtual Couponrate Couponrate { get; set; }
        public virtual cuponsGroupPrinted cuponsGroupPrinted { get; set; }
        public virtual user user { get; set; }
    }
}
