//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuponesEntagen
    {
        public long id_op { get; set; }
        public int Proveedor { get; set; }
        public string Recibio { get; set; }
        public string Sector { get; set; }
        public long CuponInicial { get; set; }
        public long CuponFinal { get; set; }
        public string Status { get; set; }
        public string Obs { get; set; }
        public System.DateTime Fechaop { get; set; }
        public string id_usuario { get; set; }
    }
}
