//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuponesBloqueo
    {
        public string Sector { get; set; }
        public long Numero { get; set; }
        public string Bloquea { get; set; }
        public string Razon { get; set; }
        public string Status { get; set; }
        public System.DateTime Fechaop { get; set; }
        public string id_usuario { get; set; }
        public Nullable<System.DateTime> FechaEdit { get; set; }
        public string id_usuarioedit { get; set; }
    }
}
