//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuponsGroupPrinted
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuponsGroupPrinted()
        {
            this.Cupons = new HashSet<Cupon>();
        }
    
        public int Id { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Printed { get; set; }
        public Nullable<System.DateTime> PrintedDate { get; set; }
        public bool Deliver { get; set; }
        public Nullable<System.DateTime> DeliverDate { get; set; }
        public bool Active { get; set; }
        public string GroupFolio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cupon> Cupons { get; set; }
    }
}
