//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CxC
    {
        public string Id_Op { get; set; }
        public string Id_Tienda { get; set; }
        public string Id_Proveedor { get; set; }
        public string TipoDoc { get; set; }
        public string No_Doc { get; set; }
        public string Referencia { get; set; }
        public string Control { get; set; }
        public string CHEQUE { get; set; }
        public string CUENTA { get; set; }
        public string BANCO { get; set; }
        public decimal Cargo { get; set; }
        public decimal Abono { get; set; }
        public decimal Saldo { get; set; }
        public System.DateTime Fechaop { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public string Id_Usuario { get; set; }
        public Nullable<int> Moneda { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Status { get; set; }
        public string Observaciones { get; set; }
    }
}
