//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class desbloqueo
    {
        public string taxi { get; set; }
        public string chofer { get; set; }
        public string economico { get; set; }
        public string mensaje { get; set; }
        public System.DateTime fecha { get; set; }
        public string detener { get; set; }
        public string id_secretaria { get; set; }
        public string secretaria { get; set; }
        public bool delsistema { get; set; }
        public bool temporal { get; set; }
        public string folio { get; set; }
        public string id_usuario { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fechacompletaserver { get; set; }
        public string usuarioultimaedicion { get; set; }
        public System.DateTime fcsdesbloqueo { get; set; }
        public string id_usuariodesbloqueo { get; set; }
        public string usuariodesbloqueo { get; set; }
    }
}
