//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string url { get; set; }
        public string bucket { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime dateDeleted { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> id_accident { get; set; }
        public Nullable<int> id_report { get; set; }
    
        public virtual accident accident { get; set; }
        public virtual report report { get; set; }
    }
}
