//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmplaRestriccion
    {
        public decimal Id_Servicio { get; set; }
        public string Id_Marca { get; set; }
        public string Id_Modelo { get; set; }
        public Nullable<int> AutoAno { get; set; }
        public string Motor { get; set; }
        public string No_Serie { get; set; }
        public string Motivo { get; set; }
        public string Avisar_a { get; set; }
        public string Telefono { get; set; }
        public Nullable<System.DateTime> FechaOp { get; set; }
    }
}
