//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class emplaBitacora
    {
        public int id { get; set; }
        public string objPre { get; set; }
        public string objPos { get; set; }
        public string movBy { get; set; }
        public Nullable<System.DateTime> movDate { get; set; }
        public decimal id_emplacamiento { get; set; }
        public string action { get; set; }
    
        public virtual Emplacamiento Emplacamiento { get; set; }
    }
}
