//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class emplacambioplacas_log
    {
        public int idcambio { get; set; }
        public decimal economico { get; set; }
        public decimal id_opemplacamiento { get; set; }
        public string placaanterior { get; set; }
        public string placanueva { get; set; }
        public System.DateTime fecha { get; set; }
        public string id_usuario { get; set; }
        public string usuario { get; set; }
    }
}
