//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emplacamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Emplacamiento()
        {
            this.emplaBitacoras = new HashSet<emplaBitacora>();
        }
    
        public decimal Id_Op { get; set; }
        public decimal No_Economico { get; set; }
        public string Nombre { get; set; }
        public string Nombre2 { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public string Propiedad { get; set; }
        public string Operacion { get; set; }
        public string Id_Mov { get; set; }
        public string Id_Marca { get; set; }
        public string Id_Modelo { get; set; }
        public int AutoAno { get; set; }
        public string Motor { get; set; }
        public string No_Serie { get; set; }
        public string Placas { get; set; }
        public int Capacidad { get; set; }
        public string EconoResp { get; set; }
        public string Responsable { get; set; }
        public string TitularEmpla { get; set; }
        public string TitularRentas { get; set; }
        public string TitularCT { get; set; }
        public string TitularOtro { get; set; }
        public string Observaciones { get; set; }
        public string Status { get; set; }
        public bool Bloqueado { get; set; }
        public Nullable<bool> Protegido { get; set; }
        public Nullable<System.DateTime> FechaOp { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
        public string Id_Usuario { get; set; }
        public string Id_UsuarioEdit { get; set; }
        public string resp_telefono { get; set; }
        public string resp_celular { get; set; }
        public string poliza { get; set; }
        public string tipopoliza { get; set; }
        public string aseguradora { get; set; }
        public Nullable<System.DateTime> vencepoliza { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emplaBitacora> emplaBitacoras { get; set; }
    }
}
