//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmplaProtegido
    {
        public decimal Id_Op { get; set; }
        public Nullable<decimal> No_Economico { get; set; }
        public string Nombre { get; set; }
        public string Propiedad { get; set; }
        public string Id_Marca { get; set; }
        public string Id_Modelo { get; set; }
        public Nullable<int> AutoAno { get; set; }
        public string Motor { get; set; }
        public string No_Serie { get; set; }
        public string Placas { get; set; }
        public Nullable<int> Capacidad { get; set; }
        public Nullable<decimal> EconoResp { get; set; }
        public string Responsable { get; set; }
        public Nullable<int> TipoResponsable { get; set; }
        public string Motivo { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> HoraInicio { get; set; }
        public Nullable<System.DateTime> FechaTermina { get; set; }
        public Nullable<System.DateTime> HoraTermina { get; set; }
        public string Id_Usuario { get; set; }
        public string Id_UsuarioEdit { get; set; }
    }
}
