//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class entregatarifarios_1
    {
        public int id_op { get; set; }
        public string tipo { get; set; }
        public string gafete { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_entrega { get; set; }
        public string id_usuario_entrega { get; set; }
        public string pc_entrega { get; set; }
    }
}
