//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class entregapavos_activacion_1
    {
        public int id { get; set; }
        public System.DateTime fechainicia { get; set; }
        public System.DateTime fechatermina { get; set; }
        public string passwordreimpresion { get; set; }
    }
}
