//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntradasySalida
    {
        public System.DateTime fecha { get; set; }
        public System.DateTime hora { get; set; }
        public string id_usuario { get; set; }
        public string tipo { get; set; }
        public string ubicacion { get; set; }
        public System.DateTime fechacompletaserver { get; set; }
    }
}
