//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamenesClinica
    {
        public string Id_Op { get; set; }
        public string Nombre { get; set; }
        public decimal Importe { get; set; }
        public System.DateTime FechaOp { get; set; }
        public System.DateTime HoraOp { get; set; }
        public string Status { get; set; }
        public int Control { get; set; }
        public Nullable<System.DateTime> FechaTrans { get; set; }
        public Nullable<System.DateTime> HoraTrans { get; set; }
        public string StatusOp { get; set; }
    }
}
