//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXAMCLPAGO
    {
        public string ID_OP { get; set; }
        public string EXAMEN { get; set; }
        public string RESPONSABLE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> FECHAOP { get; set; }
        public string CHEQUE { get; set; }
        public int CONTROL { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public Nullable<System.DateTime> fechaCheque { get; set; }
    }
}
