//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExistenciaFisica
    {
        public int Id_Tienda { get; set; }
        public string Id_Producto { get; set; }
        public string Descripcion { get; set; }
        public string Id_Proveedor { get; set; }
        public int Exist { get; set; }
        public int Existfisica { get; set; }
        public int Diferencia { get; set; }
        public decimal Costo { get; set; }
    }
}
