//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDI_NE_entregado
    {
        public string clave_cargo { get; set; }
        public string tipo { get; set; }
        public System.DateTime fechaini { get; set; }
        public Nullable<System.DateTime> fechafin { get; set; }
        public decimal cuotas_pagadas { get; set; }
        public decimal cuotas_importe { get; set; }
    }
}
