//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDI_NE_soc_turnados
    {
        public string clave_cargo { get; set; }
        public string socio { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_entra_cobro { get; set; }
    }
}
