//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FISC_DOCUMENTACION
    {
        public Nullable<double> Numero { get; set; }
        public bool SOLOLIBRETA { get; set; }
        public bool FOTO { get; set; }
        public bool T_TRIBUT { get; set; }
        public bool RFC { get; set; }
        public bool CURP { get; set; }
        public string OBS { get; set; }
    }
}
