//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormasPago
    {
        public string Id_FormaPago { get; set; }
        public string Descripcion { get; set; }
        public string Etiqueta { get; set; }
        public bool SolicitaRef { get; set; }
        public bool Divisa { get; set; }
        public decimal TipoCam { get; set; }
        public System.DateTime FechaOp { get; set; }
        public System.DateTime FechaEdit { get; set; }
        public string Id_Usuario { get; set; }
    }
}
