//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fotoid
    {
        public string gafete { get; set; }
        public System.DateTime fechaop { get; set; }
        public System.DateTime horaop { get; set; }
        public string id_usuario { get; set; }
        public Nullable<System.DateTime> fechaedit { get; set; }
        public string id_usuarioedit { get; set; }
        public int control { get; set; }
    }
}
