//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistAsistencia
    {
        public string Gafete { get; set; }
        public string Tipo { get; set; }
        public string Taxi { get; set; }
        public string Turno { get; set; }
        public System.DateTime FechaReporte { get; set; }
        public string Concepto { get; set; }
        public string Ticket { get; set; }
        public Nullable<System.DateTime> FechaOp { get; set; }
        public Nullable<int> id_permission { get; set; }
        public string mov { get; set; }
        public string autor { get; set; }
    }
}
