//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class historyreport
    {
        public int id { get; set; }
        public string objectModel { get; set; }
        public string EditBy { get; set; }
        public string EditedBy { get; set; }
        public System.DateTime EditedDate { get; set; }
        public int reportId { get; set; }
    
        public virtual report report { get; set; }
    }
}
