//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class incident
    {
        public int id { get; set; }
        public int operatorgeneral_id { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public System.DateTime edited_date { get; set; }
        public string edited_by { get; set; }
        public int company_created_id { get; set; }
        public string description { get; set; }
        public int PerfilID { get; set; }
        public bool active { get; set; }
    
        public virtual company company { get; set; }
        public virtual operatorgeneral operatorgeneral { get; set; }
    }
}
