//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class medical_records
    {
        public int id { get; set; }
        public Nullable<int> holder_id { get; set; }
        public Nullable<int> family_member_id { get; set; }
        public Nullable<System.DateTime> record_date { get; set; }
        public string notes { get; set; }
        public string allergies { get; set; }
        public string conditions { get; set; }
        public string medications { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> height { get; set; }
        public string chronic_issues { get; set; }
    
        public virtual family_members family_members { get; set; }
        public virtual user user { get; set; }
    }
}
