//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensajesguardado
    {
        public string TAXI { get; set; }
        public string CHOFER { get; set; }
        public string ECONOMICO { get; set; }
        public string MENSAJE { get; set; }
        public System.DateTime FECHA { get; set; }
        public string DETENER { get; set; }
        public string ID_SECRETARIA { get; set; }
        public string SECRETARIA { get; set; }
        public bool DELSISTEMA { get; set; }
        public bool TEMPORAL { get; set; }
        public string FOLIO { get; set; }
        public string ID_USUARIO { get; set; }
        public string USUARIO { get; set; }
    }
}
