//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosDetalle
    {
        public string Id_Producto { get; set; }
        public string Id_Op { get; set; }
        public decimal Entrada { get; set; }
        public decimal Salida { get; set; }
        public decimal Venta { get; set; }
        public decimal Costo { get; set; }
        public decimal CostoUni { get; set; }
    }
}
