//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public string Id_Op { get; set; }
        public string Id_Tienda { get; set; }
        public string Id_Mov { get; set; }
        public string Tipo { get; set; }
        public string Referencia { get; set; }
        public string EnviadoA { get; set; }
        public decimal ImpVenta { get; set; }
        public decimal ImpCosto { get; set; }
        public decimal Indirecto { get; set; }
        public System.DateTime FechaOp { get; set; }
        public System.DateTime HoraOp { get; set; }
        public string Id_Usuario { get; set; }
        public string Observ { get; set; }
    }
}
