//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Network_capturist
    {
        public int id { get; set; }
        public int id_Capturist { get; set; }
        public int id_Network { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime edited_at { get; set; }
        public string created_by { get; set; }
        public string edited_by { get; set; }
    
        public virtual Capturist Capturist { get; set; }
        public virtual network network { get; set; }
    }
}
