//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class occupationsUsersList
    {
        public int id { get; set; }
        public int occupationId { get; set; }
        public int userId { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> isValid { get; set; }
    
        public virtual occupation occupation { get; set; }
        public virtual user user { get; set; }
    }
}
