//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operadores_Baja_Datos
    {
        public long control { get; set; }
        public System.DateTime fecha_insert { get; set; }
        public bool baja_por_faltas { get; set; }
        public bool datos_regresados { get; set; }
        public Nullable<System.DateTime> fecha_regreso { get; set; }
        public string id_usuario_regreso { get; set; }
        public string CHOFER { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string SOBRENOMB { get; set; }
        public string SEXO { get; set; }
        public Nullable<System.DateTime> FECHANAC { get; set; }
        public string LUGARNAC { get; set; }
        public string EDOCIVIL { get; set; }
        public string CREDELECTOR { get; set; }
        public string SECCION { get; set; }
        public string OCUPACION { get; set; }
        public string TIPOSANGRE { get; set; }
        public string CARTILLA { get; set; }
        public string ALERGIAS { get; set; }
        public string ESCOLARIDAD { get; set; }
        public string CONYUGE { get; set; }
        public string TELEFONO { get; set; }
        public Nullable<bool> FONDDEF { get; set; }
        public string STATUS { get; set; }
        public string SOC_ALTA { get; set; }
        public Nullable<System.DateTime> FECHAING { get; set; }
        public string PATRON { get; set; }
        public string DOMICACT { get; set; }
        public string CIUDADACT { get; set; }
        public string DOMICANT { get; set; }
        public string CIUDADANT { get; set; }
        public string LICENCIA { get; set; }
        public Nullable<System.DateTime> LICVENCE { get; set; }
        public string RFC { get; set; }
        public Nullable<System.DateTime> FECHABAJ { get; set; }
        public string OBS { get; set; }
        public string COMEN1 { get; set; }
        public Nullable<System.DateTime> FECHAOP { get; set; }
        public string ID_USUARIO { get; set; }
        public Nullable<System.DateTime> FECHAEDIT { get; set; }
        public string ID_USUARIOEDIT { get; set; }
        public Nullable<System.DateTime> FECHAREACTIVACION { get; set; }
        public Nullable<decimal> FIANZA { get; set; }
        public string Mayacaribe { get; set; }
        public string UltTaxi { get; set; }
        public string ULTTURNO { get; set; }
        public string SECRETARIA { get; set; }
        public string PUESTO { get; set; }
        public Nullable<decimal> PosicionPadron { get; set; }
        public Nullable<decimal> postemp { get; set; }
        public string strenta { get; set; }
        public bool impacto { get; set; }
    }
}
