//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class operatorgeneral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public operatorgeneral()
        {
            this.incidents = new HashSet<incident>();
        }
    
        public int id { get; set; }
        public string Firstname { get; set; }
        public string LastnameF { get; set; }
        public string LastnameM { get; set; }
        public string curp { get; set; }
        public int company_created_id { get; set; }
        public int PerfilID { get; set; }
        public Nullable<int> userId { get; set; }
        public bool active { get; set; }
        public System.DateTime created_date { get; set; }
        public string created_by { get; set; }
        public System.DateTime edited_date { get; set; }
        public string edited_by { get; set; }
        public string urlImage { get; set; }
    
        public virtual company company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<incident> incidents { get; set; }
        public virtual user user { get; set; }
    }
}
