//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagocupone
    {
        public string id_op { get; set; }
        public string gafete { get; set; }
        public string sector { get; set; }
        public long numero { get; set; }
        public string perforacion { get; set; }
        public decimal importepago { get; set; }
        public int proveedor { get; set; }
        public System.DateTime fechaop { get; set; }
        public System.DateTime horaop { get; set; }
        public string id_usuario { get; set; }
        public string status { get; set; }
        public string nofactura { get; set; }
        public Nullable<System.DateTime> fechafactura { get; set; }
        public string id_usuariofactura { get; set; }
    }
}
