//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PanicAlert
    {
        public int id { get; set; }
        public string phone { get; set; }
        public string FirstName { get; set; }
        public string LastNameMother { get; set; }
        public string LastNameFather { get; set; }
        public Nullable<int> id_op { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_log { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
        public Nullable<bool> active { get; set; }
        public string editedBy { get; set; }
        public Nullable<System.DateTime> editedAt { get; set; }
        public Nullable<int> ReportTypeID { get; set; }
        public Nullable<int> reportID { get; set; }
        public Nullable<int> accidentID { get; set; }
        public Nullable<int> ScannerEventID { get; set; }
        public Nullable<int> panicAlertReportID { get; set; }
    
        public virtual accident accident { get; set; }
        public virtual panicAlertReport panicAlertReport { get; set; }
        public virtual ReportType ReportType { get; set; }
        public virtual report report { get; set; }
        public virtual ScannerEvent ScannerEvent { get; set; }
    }
}
