//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class panicAlertReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public panicAlertReport()
        {
            this.PanicAlerts = new HashSet<PanicAlert>();
        }
    
        public int id { get; set; }
        public string subject { get; set; }
        public string reason { get; set; }
        public string description { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> dateEdited { get; set; }
        public string CreatedBy { get; set; }
        public string editedBy { get; set; }
        public bool active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PanicAlert> PanicAlerts { get; set; }
    }
}
