//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosReal
    {
        public string ID_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ID_PROVEEDOR { get; set; }
        public string PROVEEDOR { get; set; }
        public string ID_DEPTO { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string ID_FAMILIA { get; set; }
        public string FAMILIA { get; set; }
        public decimal EXIST { get; set; }
        public decimal VENTA { get; set; }
        public decimal MAXIMO { get; set; }
        public decimal PEDIDOSUG { get; set; }
        public decimal PEDIR { get; set; }
        public decimal PRECIOVENTA { get; set; }
        public decimal COSTOULTIMO { get; set; }
        public Nullable<System.DateTime> FECHAULTVENTA { get; set; }
        public decimal IMPPEDIDO { get; set; }
    }
}
