//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public string ID_OP { get; set; }
        public string ID_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal CANT { get; set; }
        public decimal CANCDEV { get; set; }
        public decimal IMPORTE { get; set; }
        public decimal IMPCANCDEV { get; set; }
        public decimal COSTOIMPORTE { get; set; }
        public decimal DIFERENCIA { get; set; }
        public string ID_DEPTO { get; set; }
        public string DEPARTAMENTO { get; set; }
        public string ID_FAMILIA { get; set; }
        public string FAMILIA { get; set; }
        public System.DateTime HORAOP { get; set; }
        public string ID_PROVEEDOR { get; set; }
        public string PROVEEDOR { get; set; }
        public string ID_VENDEDOR { get; set; }
        public string VENDEDOR { get; set; }
        public string IVA { get; set; }
        public string CRITERIOGRUPO { get; set; }
        public bool TIPOCOMISION { get; set; }
        public decimal COMISION { get; set; }
        public decimal MAXIMO { get; set; }
        public decimal EXIST { get; set; }
        public decimal COSTOULTIMO { get; set; }
        public Nullable<System.DateTime> FECHAINI { get; set; }
        public Nullable<System.DateTime> FECHAFIN { get; set; }
        public Nullable<System.DateTime> FECHAULTVENTA { get; set; }
    }
}
