//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilDeComando
    {
        public string Id_Usuario { get; set; }
        public string Id_Modulo { get; set; }
        public string Id_Comando { get; set; }
        public bool Prohibido { get; set; }
    }
}
