//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliticasVenta
    {
        public string Id_Politica { get; set; }
        public string PoliticaDesc { get; set; }
        public decimal DecuentoMarca { get; set; }
        public decimal ComisionPrimerNivel { get; set; }
        public decimal DescuentoGerente { get; set; }
        public decimal ComisionSegundoNivel { get; set; }
        public decimal DescuentoEspecial { get; set; }
        public decimal ComisionTercerNivel { get; set; }
        public string Ciudad { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observaciones { get; set; }
    }
}
