//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class poll
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int id_telephoneoperators { get; set; }
        public int id_userPhone { get; set; }
        public int id_telephone_campaign { get; set; }
        public int quest1 { get; set; }
        public string quest2 { get; set; }
        public string quest3 { get; set; }
        public string quest4 { get; set; }
        public string quest5 { get; set; }
        public Nullable<bool> quest6 { get; set; }
        public string quest7 { get; set; }
        public string quest8 { get; set; }
        public string quest9 { get; set; }
        public string quest10 { get; set; }
        public int tend { get; set; }
        public string quest12 { get; set; }
        public Nullable<int> id_categoriesQuestProblems_1 { get; set; }
        public Nullable<int> id_categoriesQuestProblems_2 { get; set; }
        public Nullable<int> id_categoriesQuestProblems_3 { get; set; }
    
        public virtual candidate candidate { get; set; }
        public virtual categoriesQuestProblem categoriesQuestProblem { get; set; }
        public virtual categoriesQuestProblem categoriesQuestProblem1 { get; set; }
        public virtual categoriesQuestProblem categoriesQuestProblem2 { get; set; }
        public virtual telephoneoperator telephoneoperator { get; set; }
        public virtual telephone_campaign telephone_campaign { get; set; }
        public virtual userPhone userPhone { get; set; }
        public virtual user user { get; set; }
    }
}
