//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int id { get; set; }
        public string preBanner { get; set; }
        public string banner { get; set; }
        public string url { get; set; }
        public string title { get; set; }
        public string details { get; set; }
        public System.DateTime datecreate { get; set; }
        public Nullable<System.DateTime> dateupdate { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
