//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public profile()
        {
            this.userProfiles = new HashSet<userProfile>();
        }
    
        public int profileId { get; set; }
        public int systemId { get; set; }
        public string name { get; set; }
        public int objectACLId { get; set; }
        public int objectAcl_objectACLId { get; set; }
    
        public virtual objectAcl objectAcl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userProfile> userProfiles { get; set; }
    }
}
