//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radio_Taxi
    {
        public string GAFETE { get; set; }
        public Nullable<System.DateTime> FECHAINGRESO { get; set; }
        public Nullable<System.DateTime> FECHABAJA { get; set; }
        public int FOLIO { get; set; }
    }
}
