//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDC_esquema_convenios
    {
        public string id_concepto { get; set; }
        public int Folio { get; set; }
        public string Id_Producto { get; set; }
        public decimal Importe { get; set; }
    }
}
