//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public report()
        {
            this.commentsreports = new HashSet<commentsreport>();
            this.documents = new HashSet<document>();
            this.historyreports = new HashSet<historyreport>();
            this.PanicAlerts = new HashSet<PanicAlert>();
            this.report_Files = new HashSet<report_Files>();
            this.trackings = new HashSet<tracking>();
        }
    
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public int statusReportId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime EditedDate { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public string place { get; set; }
        public System.DateTime ServiceDate { get; set; }
        public string economic { get; set; }
        public string description { get; set; }
        public int priorityId { get; set; }
        public int originReportId { get; set; }
        public int reportTypeId { get; set; }
        public Nullable<System.DateTime> dateDeleted { get; set; }
        public string DeletedBy { get; set; }
        public string title { get; set; }
        public string descriptionPlace { get; set; }
        public Nullable<int> descriptionLossId { get; set; }
        public Nullable<int> descriptionOperatorId { get; set; }
        public Nullable<int> descriptionVehicleId { get; set; }
        public Nullable<int> clientId { get; set; }
        public Nullable<int> authyID { get; set; }
        public string authyName { get; set; }
        public string authyAsigmentBy { get; set; }
        public Nullable<System.DateTime> authyAsigmentDate { get; set; }
        public bool isActive { get; set; }
        public Nullable<System.DateTime> closeDate { get; set; }
        public string closeBy { get; set; }
    
        public virtual client client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commentsreport> commentsreports { get; set; }
        public virtual descriptionLoss descriptionLoss { get; set; }
        public virtual descriptionOperator descriptionOperator { get; set; }
        public virtual descriptionVehicle descriptionVehicle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<document> documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historyreport> historyreports { get; set; }
        public virtual originReport originReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PanicAlert> PanicAlerts { get; set; }
        public virtual priority priority { get; set; }
        public virtual ReportType ReportType { get; set; }
        public virtual statusReport statusReport { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_Files> report_Files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tracking> trackings { get; set; }
    }
}
