//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class reportService
    {
        public int id { get; set; }
        public int value { get; set; }
        public Nullable<int> client_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> dateEdited { get; set; }
        public string CreatedBy { get; set; }
        public string editedBy { get; set; }
        public bool active { get; set; }
    
        public virtual user user { get; set; }
    }
}
