//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_Files
    {
        public int id { get; set; }
        public Nullable<int> report_id { get; set; }
        public Nullable<int> tracking_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string url { get; set; }
        public string bucket { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> dateDeleted { get; set; }
        public string DeletedBy { get; set; }
    
        public virtual report report { get; set; }
        public virtual tracking tracking { get; set; }
    }
}
