//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class roleparam
    {
        public int id { get; set; }
        public Nullable<int> paramId { get; set; }
        public Nullable<int> roleId { get; set; }
    
        public virtual parameter parameter { get; set; }
        public virtual role role { get; set; }
    }
}
