//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScannerEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScannerEvent()
        {
            this.PanicAlerts = new HashSet<PanicAlert>();
        }
    
        public int id { get; set; }
        public string phone { get; set; }
        public Nullable<int> id_user { get; set; }
        public string partnerreferenceScan { get; set; }
        public string FirstName { get; set; }
        public string LastNameMother { get; set; }
        public string LastNameFather { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string typeScan { get; set; }
        public Nullable<int> IdPadron { get; set; }
        public Nullable<System.DateTime> dateDisable { get; set; }
        public Nullable<int> ReportTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PanicAlert> PanicAlerts { get; set; }
        public virtual ReportType ReportType { get; set; }
    }
}
