//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_LiqCobros
    {
        public string Id_Op { get; set; }
        public string Operador { get; set; }
        public string Id_Vendedor { get; set; }
        public string Id_Producto { get; set; }
        public string Id_Familia { get; set; }
        public int Cant { get; set; }
        public string Descripcion { get; set; }
        public decimal PrecioConiva { get; set; }
        public string Status { get; set; }
    }
}
