//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SD_LiqPorPagar
    {
        public string Operador { get; set; }
        public string Taxi { get; set; }
        public string OPERADORES { get; set; }
        public string Id_Producto { get; set; }
        public string Descripcion { get; set; }
        public string Id_Familia { get; set; }
        public Nullable<int> Exist { get; set; }
        public Nullable<decimal> PrecioConIva { get; set; }
        public Nullable<System.DateTime> FechaOp { get; set; }
    }
}
