//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SindLiq1
    {
        public string Taxi { get; set; }
        public string Gafete { get; set; }
        public string Descripcion { get; set; }
        public int Cant { get; set; }
        public decimal PrecioConIva { get; set; }
        public int Descuento { get; set; }
        public System.DateTime FechaOp { get; set; }
        public string Status { get; set; }
        public decimal Control { get; set; }
    }
}
