//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SistAdmCtrlLiq
    {
        public Nullable<int> Eco { get; set; }
        public Nullable<int> Id_Vehiculo { get; set; }
        public string Chofer { get; set; }
        public Nullable<System.DateTime> FechaLiq { get; set; }
        public string Turno { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public decimal Cobro { get; set; }
        public Nullable<System.DateTime> Fechacobro { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public int Control { get; set; }
    }
}
