//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SistAdmCtrlOperadore
    {
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public string Gafete { get; set; }
        public bool Activo { get; set; }
        public string Obs { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<int> Usuario { get; set; }
        public int Control { get; set; }
    }
}
