//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SistAdmCtrlServicioHead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SistAdmCtrlServicioHead()
        {
            this.SistAdmCtrlServicioDetalles = new HashSet<SistAdmCtrlServicioDetalle>();
        }
    
        public int Id_Op { get; set; }
        public Nullable<int> Id_Vehiculo { get; set; }
        public Nullable<int> Eco { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Id_Servicio { get; set; }
        public string Descirpcion { get; set; }
        public string Obs { get; set; }
        public Nullable<System.DateTime> FechaOp { get; set; }
        public Nullable<int> Usuario { get; set; }
    
        public virtual IronUser IronUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SistAdmCtrlServicioDetalle> SistAdmCtrlServicioDetalles { get; set; }
        public virtual SistAdmCtrlVehiculo SistAdmCtrlVehiculo { get; set; }
        public virtual SistAdmServiciosCatalogo SistAdmServiciosCatalogo { get; set; }
    }
}
