//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SistAdmCtrlOperadores2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SistAdmCtrlOperadores2()
        {
            this.Inventarios = new HashSet<Inventario>();
        }
    
        public string Taxi { get; set; }
        public Nullable<int> Dueño { get; set; }
        public string Operdor { get; set; }
        public string Gafete { get; set; }
        public string Tipo { get; set; }
        public string Telefono { get; set; }
        public string Turno { get; set; }
        public Nullable<double> Adeudo { get; set; }
        public Nullable<double> Importe { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public string Descanso { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public Nullable<int> Id_UsuarioBaja { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public Nullable<int> UsuarioAlta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventario> Inventarios { get; set; }
    }
}
