//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sistAdmCtrlIncidencia
    {
        public int Id_Incidencia { get; set; }
        public string Gafete { get; set; }
        public Nullable<int> Taxi { get; set; }
        public Nullable<int> Id_Vehiculo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Descripcion { get; set; }
        public string Motivo { get; set; }
        public Nullable<decimal> ImporteaDescontar { get; set; }
    }
}
