//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SistAdmCtrlVehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SistAdmCtrlVehiculo()
        {
            this.SistAdmCtrlServicioHeads = new HashSet<SistAdmCtrlServicioHead>();
        }
    
        public Nullable<int> Id_Propietario { get; set; }
        public Nullable<int> Eco { get; set; }
        public int Id_Vehiculo { get; set; }
        public string NumSerie { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public Nullable<int> Año { get; set; }
        public string Trasmision { get; set; }
        public Nullable<System.DateTime> IngresoATaxi { get; set; }
        public Nullable<double> KilometrajeInicial { get; set; }
        public Nullable<bool> TieneClima { get; set; }
        public string Aseguradora { get; set; }
        public string Poliza { get; set; }
        public string Covertura { get; set; }
        public Nullable<System.DateTime> Vence { get; set; }
        public Nullable<bool> PlacaRentada { get; set; }
        public Nullable<System.DateTime> RentaVence { get; set; }
        public Nullable<int> Usuario { get; set; }
        public Nullable<System.DateTime> Fechaop { get; set; }
        public Nullable<int> UsuarioEdit { get; set; }
        public Nullable<System.DateTime> FechaEdit { get; set; }
    
        public virtual IronUser IronUser { get; set; }
        public virtual SisAdmPropietario SisAdmPropietario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SistAdmCtrlServicioHead> SistAdmCtrlServicioHeads { get; set; }
    }
}
