//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soc_DatFiscales
    {
        public Nullable<int> Id_Op { get; set; }
        public int Numero { get; set; }
        public bool ControlFiscal { get; set; }
        public Nullable<System.DateTime> Fch_Ingreso { get; set; }
        public Nullable<System.DateTime> Fch_Alta { get; set; }
        public string RFC { get; set; }
        public string Curp { get; set; }
        public string Act_Prepon { get; set; }
        public string Oblig_Fiscal { get; set; }
        public string Dism_Fiscal { get; set; }
        public string Origen { get; set; }
        public Nullable<decimal> Inscripcion { get; set; }
        public string Rep_Nombre { get; set; }
        public string Rep_Paterno { get; set; }
        public string Rep_Materno { get; set; }
        public string Rep_RFC { get; set; }
    
        public virtual Soc_DatPersonales Soc_DatPersonales { get; set; }
    }
}
