//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soc_Head
    {
        public Nullable<short> Numero { get; set; }
        public string Asignacion { get; set; }
        public string Area { get; set; }
        public bool Bloqueo { get; set; }
        public bool RenFondDef { get; set; }
        public bool CuotaSind { get; set; }
        public bool OperaUnidad { get; set; }
        public Nullable<System.DateTime> Fch_Op { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Fch_Edit { get; set; }
        public string Usuario_edit { get; set; }
    }
}
