//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soc_Documentacion
    {
        public int Numero { get; set; }
        public Nullable<short> Grupo { get; set; }
        public string Documento { get; set; }
        public bool Entregado { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> Fch_Op { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Fch_Edit { get; set; }
        public string UsuarioEdit { get; set; }
    
        public virtual Soc_DatPersonales Soc_DatPersonales { get; set; }
    }
}
