//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soc_DomiciliosPart
    {
        public Nullable<int> Id_Op { get; set; }
        public int Numero { get; set; }
        public string Domicilio { get; set; }
        public string Colonia { get; set; }
        public string Referencia { get; set; }
        public string Localidad { get; set; }
        public string Cp { get; set; }
        public string Municipio { get; set; }
        public string Estado { get; set; }
        public string TipoDom { get; set; }
        public string ubicacion { get; set; }
    
        public virtual Soc_DatPersonales Soc_DatPersonales { get; set; }
    }
}
