//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareasTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TareasTask()
        {
            this.TareasComuns = new HashSet<TareasComun>();
            this.TareasInvolus = new HashSet<TareasInvolu>();
        }
    
        public string Encabezado { get; set; }
        public Nullable<int> Eco { get; set; }
        public string Gafete { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Hora { get; set; }
        public System.DateTime Incia { get; set; }
        public System.DateTime Vence { get; set; }
        public string Status { get; set; }
        public string Tipo { get; set; }
        public int Id_Proy { get; set; }
        public int Id_Tarea { get; set; }
        public int Id_Usuario { get; set; }
        public Nullable<int> GrupoTipo { get; set; }
        public Nullable<bool> Servicio { get; set; }
    
        public virtual Soc_DatPersonales Soc_DatPersonales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TareasComun> TareasComuns { get; set; }
        public virtual TareasHead TareasHead { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TareasInvolu> TareasInvolus { get; set; }
        public virtual TGrupotipo TGrupotipo { get; set; }
        public virtual TUsuario TUsuario { get; set; }
    }
}
