//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareasHead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TareasHead()
        {
            this.TareasTasks = new HashSet<TareasTask>();
        }
    
        public int Id_Op { get; set; }
        public string Tipo { get; set; }
        public int Propietario { get; set; }
        public string Origen { get; set; }
        public string Proyecto { get; set; }
        public int Comision { get; set; }
        public int Departamento { get; set; }
        public string Instruciones { get; set; }
        public int Etapa { get; set; }
        public Nullable<System.DateTime> Inicia { get; set; }
        public Nullable<System.DateTime> Vence { get; set; }
        public string Aviso { get; set; }
        public string Prioridad { get; set; }
        public string Avance { get; set; }
        public string Status { get; set; }
        public System.DateTime FechaOp { get; set; }
    
        public virtual TareasComi TareasComi { get; set; }
        public virtual TareasEtapa TareasEtapa { get; set; }
        public virtual TUsuario TUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TareasTask> TareasTasks { get; set; }
    }
}
