//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareasComun
    {
        public string Mensaje { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public string Anexo { get; set; }
        public int Id_Usuario { get; set; }
        public int Control { get; set; }
        public int Id_Tarea { get; set; }
    
        public virtual TareasTask TareasTask { get; set; }
    }
}
