//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifaCupone
    {
        public string Sector { get; set; }
        public int Proveedor { get; set; }
        public string Perforacion { get; set; }
        public decimal Pago { get; set; }
        public decimal Factura { get; set; }
        public System.DateTime Fechaop { get; set; }
        public string Id_usuario { get; set; }
        public string Status { get; set; }
        public int Control { get; set; }
    }
}
