//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbitacora
    {
        public string Bitacora { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Hora { get; set; }
        public System.DateTime Incia { get; set; }
        public System.DateTime Vence { get; set; }
        public string Status { get; set; }
        public string Tipo { get; set; }
        public string Id_Tienda { get; set; }
        public int Id_Bitacora { get; set; }
        public int Id_Usuario { get; set; }
    }
}
