//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class telephone_campaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public telephone_campaign()
        {
            this.polls = new HashSet<poll>();
            this.userPhone_telephoneoperators_campaign = new HashSet<userPhone_telephoneoperators_campaign>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime datecreated { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> dateEdited { get; set; }
        public string Edited_by { get; set; }
        public Nullable<bool> active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<poll> polls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userPhone_telephoneoperators_campaign> userPhone_telephoneoperators_campaign { get; set; }
    }
}
