//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempFacturarCupone
    {
        public string id_oppago { get; set; }
        public string sector { get; set; }
        public long numero { get; set; }
        public string perforacion { get; set; }
        public decimal importepago { get; set; }
        public decimal importefacturar { get; set; }
        public System.DateTime fechapago { get; set; }
        public bool facturar { get; set; }
    }
}
