//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempVentasDetalle
    {
        public System.DateTime Fecha { get; set; }
        public string Proveedor { get; set; }
        public string Id_Op { get; set; }
        public string Id_Producto { get; set; }
        public string Id_Proveedor { get; set; }
        public string Id_Depto { get; set; }
        public string Id_Familia { get; set; }
        public string Id_Subfamilia { get; set; }
        public int Cant { get; set; }
        public string Descripcion { get; set; }
        public decimal PrecioConiva { get; set; }
        public decimal Descporc { get; set; }
        public decimal Descimp { get; set; }
        public decimal PrecioVenta { get; set; }
        public decimal Importe { get; set; }
        public decimal PorcIva { get; set; }
        public decimal Iva { get; set; }
        public decimal IpsPoc { get; set; }
        public decimal Ips { get; set; }
        public decimal PrecioSinIva { get; set; }
        public decimal DescimpSinIva { get; set; }
        public decimal PrecioVentaSinIva { get; set; }
        public decimal ImporteSinIva { get; set; }
        public decimal Costo { get; set; }
        public decimal CostoImorte { get; set; }
        public decimal Devueltos { get; set; }
    }
}
