//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tracking()
        {
            this.report_Files = new HashSet<report_Files>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string createdBy { get; set; }
        public System.DateTime dateDeleted { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<int> report_id { get; set; }
    
        public virtual report report { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_Files> report_Files { get; set; }
    }
}
