//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int creditcardsId { get; set; }
        public string ticket { get; set; }
        public decimal amount { get; set; }
        public string status { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<bool> active { get; set; }
        public string carbuy { get; set; }
    
        public virtual creditcard creditcard { get; set; }
        public virtual user user { get; set; }
    }
}
