//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUsuario()
        {
            this.TareasHeads = new HashSet<TareasHead>();
            this.TareasTasks = new HashSet<TareasTask>();
        }
    
        public int Id_Usuario { get; set; }
        public string Usuario { get; set; }
        public string Nombre { get; set; }
        public string Id_Tienda { get; set; }
        public string Puesto { get; set; }
        public Nullable<int> Id_DeptoRh { get; set; }
        public string PassWord { get; set; }
        public System.DateTime FechaOp { get; set; }
        public Nullable<int> UsuarioOp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TareasHead> TareasHeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TareasTask> TareasTasks { get; set; }
    }
}
