//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class userGeolocation
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public double Latitud { get; set; }
        public double Longitud { get; set; }
        public double speed { get; set; }
        public System.Data.Entity.Spatial.DbGeography geolocation { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string type { get; set; }
        public string OpenPayOrderId { get; set; }
    
        public virtual user user { get; set; }
    }
}
