//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class userOccupation
    {
        public int id { get; set; }
        public int userId { get; set; }
        public System.DateTime dtCreated { get; set; }
        public Nullable<int> positionId { get; set; }
        public Nullable<int> academicGradeId { get; set; }
    
        public virtual academicGrade academicGrade { get; set; }
        public virtual Position Position { get; set; }
        public virtual user user { get; set; }
    }
}
