//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class userPhone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userPhone()
        {
            this.polls = new HashSet<poll>();
            this.userPhone_telephoneoperators_campaign = new HashSet<userPhone_telephoneoperators_campaign>();
        }
    
        public int id { get; set; }
        public int userId { get; set; }
        public string phone { get; set; }
        public int phoneTypeId { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> isValid { get; set; }
        public Nullable<int> source { get; set; }
    
        public virtual phoneType phoneType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<poll> polls { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userPhone_telephoneoperators_campaign> userPhone_telephoneoperators_campaign { get; set; }
    }
}
