//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGrouping
    {
        public int id { get; set; }
        public string folio { get; set; }
        public string position { get; set; }
        public int id_grouping { get; set; }
        public int id_user { get; set; }
        public bool isActive { get; set; }
        public System.DateTime datecreated { get; set; }
    
        public virtual grouping grouping { get; set; }
        public virtual user user { get; set; }
    }
}
