//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class userAddress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userAddress()
        {
            this.address_sectors = new HashSet<address_sectors>();
            this.assignments = new HashSet<assignment>();
        }
    
        public int id { get; set; }
        public int userId { get; set; }
        public string supermanzana { get; set; }
        public string manzana { get; set; }
        public string lote { get; set; }
        public string street { get; set; }
        public string interiorNumber { get; set; }
        public string colony { get; set; }
        public string postalCode { get; set; }
        public Nullable<int> sectionId { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public string address { get; set; }
        public string address2 { get; set; }
        public Nullable<int> stateId { get; set; }
        public Nullable<int> cityId { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<int> zoneId { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> editDate { get; set; }
        public string createdBy { get; set; }
        public string editBy { get; set; }
        public Nullable<bool> isValid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<address_sectors> address_sectors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assignment> assignments { get; set; }
        public virtual city city { get; set; }
        public virtual state state { get; set; }
        public virtual user user { get; set; }
        public virtual zone zone { get; set; }
    }
}
