//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class userProfile
    {
        public int userId { get; set; }
        public int profileId { get; set; }
        public Nullable<int> profile_profileId { get; set; }
        public Nullable<int> users_userId { get; set; }
    
        public virtual profile profile { get; set; }
        public virtual userlog userlog { get; set; }
    }
}
