//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.C_permissions = new HashSet<C_permissions>();
            this.accidents = new HashSet<accident>();
            this.amazonPictures = new HashSet<amazonPicture>();
            this.assignments = new HashSet<assignment>();
            this.box_user = new HashSet<box_user>();
            this.cards = new HashSet<card>();
            this.Christmasgifts = new HashSet<Christmasgift>();
            this.CouponPayments = new HashSet<CouponPayment>();
            this.creditcards = new HashSet<creditcard>();
            this.Cupons = new HashSet<Cupon>();
            this.emails = new HashSet<email>();
            this.family_members = new HashSet<family_members>();
            this.hardvotes = new HashSet<hardvote>();
            this.medical_records = new HashSet<medical_records>();
            this.memberships = new HashSet<membership>();
            this.networks = new HashSet<network>();
            this.occupationsUsersLists = new HashSet<occupationsUsersList>();
            this.operatorgenerals = new HashSet<operatorgeneral>();
            this.payrollCapturists = new HashSet<payrollCapturist>();
            this.polls = new HashSet<poll>();
            this.rates = new HashSet<rate>();
            this.reports = new HashSet<report>();
            this.reportServices = new HashSet<reportService>();
            this.reportUnits = new HashSet<reportUnit>();
            this.transactions = new HashSet<transaction>();
            this.userAddresses = new HashSet<userAddress>();
            this.userFamilies = new HashSet<userFamily>();
            this.userGeolocations = new HashSet<userGeolocation>();
            this.UserGroupings = new HashSet<UserGrouping>();
            this.UserOwners = new HashSet<UserOwner>();
            this.UserOwners1 = new HashSet<UserOwner>();
            this.userPhones = new HashSet<userPhone>();
            this.userPrintedCards = new HashSet<userPrintedCard>();
            this.visits = new HashSet<visit>();
        }
    
        public int id { get; set; }
        public string partnerReference { get; set; }
        public string firstName { get; set; }
        public string lastNameF { get; set; }
        public string lastNameM { get; set; }
        public System.DateTime createdDt { get; set; }
        public int partnerTypeId { get; set; }
        public string birthPlace { get; set; }
        public int sex { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public int userTypeId { get; set; }
        public Nullable<System.DateTime> dtLastUpdate { get; set; }
        public int relationShipStatusId { get; set; }
        public short statusId { get; set; }
        public Nullable<bool> cafecude { get; set; }
        public Nullable<bool> at { get; set; }
        public Nullable<bool> active { get; set; }
        public string reason { get; set; }
        public string createdBy { get; set; }
        public string editBy { get; set; }
        public Nullable<int> meeting { get; set; }
        public Nullable<bool> death { get; set; }
        public Nullable<bool> enemy { get; set; }
        public Nullable<bool> payroll { get; set; }
        public Nullable<bool> ttesoc { get; set; }
        public Nullable<int> employee { get; set; }
        public Nullable<bool> employees { get; set; }
        public Nullable<bool> noVote { get; set; }
        public Nullable<int> sectionId { get; set; }
        public Nullable<int> candidateId { get; set; }
        public Nullable<int> candidateHardvoteId { get; set; }
        public int candidateQuizID { get; set; }
        public Nullable<int> gps_id { get; set; }
        public Nullable<bool> tsc { get; set; }
        public Nullable<bool> rt { get; set; }
        public string googleplus { get; set; }
        public string facebook { get; set; }
        public string instagram { get; set; }
        public string twitter { get; set; }
        public string ttc_soc_eco { get; set; }
        public string comments { get; set; }
        public string rfc { get; set; }
        public string ine { get; set; }
        public string curp { get; set; }
        public string recommendedBy { get; set; }
        public string openpayClientID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_permissions> C_permissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<accident> accidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<amazonPicture> amazonPictures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assignment> assignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<box_user> box_user { get; set; }
        public virtual candidate candidate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<card> cards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Christmasgift> Christmasgifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponPayment> CouponPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<creditcard> creditcards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cupon> Cupons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<email> emails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<family_members> family_members { get; set; }
        public virtual fingerInfo fingerInfo { get; set; }
        public virtual gp gp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hardvote> hardvotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<medical_records> medical_records { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<membership> memberships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<network> networks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<occupationsUsersList> occupationsUsersLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<operatorgeneral> operatorgenerals { get; set; }
        public virtual partnerType partnerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payrollCapturist> payrollCapturists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<poll> polls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rate> rates { get; set; }
        public virtual relationShipStatu relationShipStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report> reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reportService> reportServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reportUnit> reportUnits { get; set; }
        public virtual sectionsTTE sectionsTTE { get; set; }
        public virtual status status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction> transactions { get; set; }
        public virtual userType userType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userAddress> userAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userFamily> userFamilies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userGeolocation> userGeolocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserGrouping> UserGroupings { get; set; }
        public virtual userHealthInformation userHealthInformation { get; set; }
        public virtual userOccupation userOccupation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOwner> UserOwners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOwner> UserOwners1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userPhone> userPhones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userPrintedCard> userPrintedCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<visit> visits { get; set; }
    }
}
