//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class userHealthInformation
    {
        public int id { get; set; }
        public string allergies { get; set; }
        public bool organDonor { get; set; }
        public int userId { get; set; }
        public Nullable<int> bloodTypeID { get; set; }
        public string descripalergies { get; set; }
    
        public virtual user user { get; set; }
        public virtual userBloodType userBloodType { get; set; }
    }
}
