//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosInternet
    {
        public string id_usuario { get; set; }
        public string Usuario { get; set; }
        public string Nombre { get; set; }
        public string Puesto { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<System.DateTime> vence { get; set; }
        public Nullable<System.DateTime> FechaOp { get; set; }
        public Nullable<System.DateTime> FechaEdit { get; set; }
        public string Id_Empresa { get; set; }
        public string Id_Nivel { get; set; }
    }
}
