//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace radiotaxi.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Venta01Entities : DbContext
    {
        public Venta01Entities()
            : base("name=Venta01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANCO> BANCOS { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Comando> Comandos { get; set; }
        public virtual DbSet<Compra> Compras { get; set; }
        public virtual DbSet<ComprasDetalle> ComprasDetalles { get; set; }
        public virtual DbSet<ComputadoraCambioVersion> ComputadoraCambioVersions { get; set; }
        public virtual DbSet<ConceptoAgrupador> ConceptoAgrupadors { get; set; }
        public virtual DbSet<Concepto> Conceptos { get; set; }
        public virtual DbSet<ConceptosCxP> ConceptosCxPs { get; set; }
        public virtual DbSet<ConceptosCxP2> ConceptosCxP2 { get; set; }
        public virtual DbSet<CUENTA> CUENTAS { get; set; }
        public virtual DbSet<CxC> CxCs { get; set; }
        public virtual DbSet<CxP> CxPs { get; set; }
        public virtual DbSet<Departamento> Departamentos { get; set; }
        public virtual DbSet<dtproperty> dtproperties { get; set; }
        public virtual DbSet<ExistenciaFisica> ExistenciaFisicas { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<FacturasDetalle> FacturasDetalles { get; set; }
        public virtual DbSet<Familia> Familias { get; set; }
        public virtual DbSet<FormasPago> FormasPagoes { get; set; }
        public virtual DbSet<Inventario> Inventarios { get; set; }
        public virtual DbSet<Modulo> Modulos { get; set; }
        public virtual DbSet<Movimiento> Movimientos { get; set; }
        public virtual DbSet<MovimientosDetalle> MovimientosDetalles { get; set; }
        public virtual DbSet<Observacione> Observaciones { get; set; }
        public virtual DbSet<PerfilDeAcceso> PerfilDeAccesoes { get; set; }
        public virtual DbSet<PerfilDeComando> PerfilDeComandoes { get; set; }
        public virtual DbSet<PoliticasVenta> PoliticasVentas { get; set; }
        public virtual DbSet<Proveedore> Proveedores { get; set; }
        public virtual DbSet<SubFamilia> SubFamilias { get; set; }
        public virtual DbSet<Tienda> Tiendas { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Vendedore> Vendedores { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
        public virtual DbSet<asistenciaTemporal> asistenciaTemporals { get; set; }
        public virtual DbSet<Bitacora> Bitacoras { get; set; }
        public virtual DbSet<Cobro> Cobros { get; set; }
        public virtual DbSet<CobrosDetalle> CobrosDetalles { get; set; }
        public virtual DbSet<Consecutivo> Consecutivos { get; set; }
        public virtual DbSet<Control> Controls { get; set; }
        public virtual DbSet<InventarioHistorico> InventarioHistoricoes { get; set; }
        public virtual DbSet<mua_V1> mua_V1 { get; set; }
        public virtual DbSet<Pedido> Pedidos { get; set; }
        public virtual DbSet<PedidosReal> PedidosReals { get; set; }
        public virtual DbSet<VentasDetalle> VentasDetalles { get; set; }
    
        public virtual int AJR_CREARPEDIDO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AJR_CREARPEDIDO");
        }
    
        public virtual int AJR_RESPALDA_INVENTARIO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AJR_RESPALDA_INVENTARIO");
        }
    
        public virtual int AJR_SALDOSXCOBRARFDIOPE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AJR_SALDOSXCOBRARFDIOPE");
        }
    
        public virtual int AJR_SALDOSXCOBRARFDISOC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AJR_SALDOSXCOBRARFDISOC");
        }
    
        public virtual int CSP_ACTUALIZACXC(string iD_OP, string iD_TIENDA, string iD_PROVEEDOR, string tIPODOC, string nO_DOC, string rEFERENCIA, string cONTROL, string cHEQUE, string cUENTA, string bANCO, Nullable<decimal> cARGO, Nullable<decimal> aBONO, Nullable<decimal> sALDO, Nullable<System.DateTime> fECHAVENCIMIENTO, Nullable<System.DateTime> fECHAOP, string iD_USUARIO, string cONDICION, Nullable<int> mONEDA, Nullable<decimal> rATE, string sTATUS)
        {
            var iD_OPParameter = iD_OP != null ?
                new ObjectParameter("ID_OP", iD_OP) :
                new ObjectParameter("ID_OP", typeof(string));
    
            var iD_TIENDAParameter = iD_TIENDA != null ?
                new ObjectParameter("ID_TIENDA", iD_TIENDA) :
                new ObjectParameter("ID_TIENDA", typeof(string));
    
            var iD_PROVEEDORParameter = iD_PROVEEDOR != null ?
                new ObjectParameter("ID_PROVEEDOR", iD_PROVEEDOR) :
                new ObjectParameter("ID_PROVEEDOR", typeof(string));
    
            var tIPODOCParameter = tIPODOC != null ?
                new ObjectParameter("TIPODOC", tIPODOC) :
                new ObjectParameter("TIPODOC", typeof(string));
    
            var nO_DOCParameter = nO_DOC != null ?
                new ObjectParameter("NO_DOC", nO_DOC) :
                new ObjectParameter("NO_DOC", typeof(string));
    
            var rEFERENCIAParameter = rEFERENCIA != null ?
                new ObjectParameter("REFERENCIA", rEFERENCIA) :
                new ObjectParameter("REFERENCIA", typeof(string));
    
            var cONTROLParameter = cONTROL != null ?
                new ObjectParameter("CONTROL", cONTROL) :
                new ObjectParameter("CONTROL", typeof(string));
    
            var cHEQUEParameter = cHEQUE != null ?
                new ObjectParameter("CHEQUE", cHEQUE) :
                new ObjectParameter("CHEQUE", typeof(string));
    
            var cUENTAParameter = cUENTA != null ?
                new ObjectParameter("CUENTA", cUENTA) :
                new ObjectParameter("CUENTA", typeof(string));
    
            var bANCOParameter = bANCO != null ?
                new ObjectParameter("BANCO", bANCO) :
                new ObjectParameter("BANCO", typeof(string));
    
            var cARGOParameter = cARGO.HasValue ?
                new ObjectParameter("CARGO", cARGO) :
                new ObjectParameter("CARGO", typeof(decimal));
    
            var aBONOParameter = aBONO.HasValue ?
                new ObjectParameter("ABONO", aBONO) :
                new ObjectParameter("ABONO", typeof(decimal));
    
            var sALDOParameter = sALDO.HasValue ?
                new ObjectParameter("SALDO", sALDO) :
                new ObjectParameter("SALDO", typeof(decimal));
    
            var fECHAVENCIMIENTOParameter = fECHAVENCIMIENTO.HasValue ?
                new ObjectParameter("FECHAVENCIMIENTO", fECHAVENCIMIENTO) :
                new ObjectParameter("FECHAVENCIMIENTO", typeof(System.DateTime));
    
            var fECHAOPParameter = fECHAOP.HasValue ?
                new ObjectParameter("FECHAOP", fECHAOP) :
                new ObjectParameter("FECHAOP", typeof(System.DateTime));
    
            var iD_USUARIOParameter = iD_USUARIO != null ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(string));
    
            var cONDICIONParameter = cONDICION != null ?
                new ObjectParameter("CONDICION", cONDICION) :
                new ObjectParameter("CONDICION", typeof(string));
    
            var mONEDAParameter = mONEDA.HasValue ?
                new ObjectParameter("MONEDA", mONEDA) :
                new ObjectParameter("MONEDA", typeof(int));
    
            var rATEParameter = rATE.HasValue ?
                new ObjectParameter("RATE", rATE) :
                new ObjectParameter("RATE", typeof(decimal));
    
            var sTATUSParameter = sTATUS != null ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_ACTUALIZACXC", iD_OPParameter, iD_TIENDAParameter, iD_PROVEEDORParameter, tIPODOCParameter, nO_DOCParameter, rEFERENCIAParameter, cONTROLParameter, cHEQUEParameter, cUENTAParameter, bANCOParameter, cARGOParameter, aBONOParameter, sALDOParameter, fECHAVENCIMIENTOParameter, fECHAOPParameter, iD_USUARIOParameter, cONDICIONParameter, mONEDAParameter, rATEParameter, sTATUSParameter);
        }
    
        public virtual int CSP_ACTUALIZACXP(string iD_OP, string iD_TIENDA, string iD_PROVEEDOR, string tIPODOC, string nO_DOC, string rEFERENCIA, string cONTROL, string cHEQUE, string cUENTA, string bANCO, Nullable<decimal> cARGO, Nullable<decimal> aBONO, Nullable<decimal> sALDO, Nullable<System.DateTime> fECHAVENCIMIENTO, Nullable<System.DateTime> fECHAOP, Nullable<System.DateTime> fECHAFACTURA, string iD_USUARIO, string cONDICION, Nullable<int> mONEDA, Nullable<decimal> rATE, string sTATUS, string oBSERVACIONES, string dEPARTAMENTO, string gRUPO, string cONCEPTO)
        {
            var iD_OPParameter = iD_OP != null ?
                new ObjectParameter("ID_OP", iD_OP) :
                new ObjectParameter("ID_OP", typeof(string));
    
            var iD_TIENDAParameter = iD_TIENDA != null ?
                new ObjectParameter("ID_TIENDA", iD_TIENDA) :
                new ObjectParameter("ID_TIENDA", typeof(string));
    
            var iD_PROVEEDORParameter = iD_PROVEEDOR != null ?
                new ObjectParameter("ID_PROVEEDOR", iD_PROVEEDOR) :
                new ObjectParameter("ID_PROVEEDOR", typeof(string));
    
            var tIPODOCParameter = tIPODOC != null ?
                new ObjectParameter("TIPODOC", tIPODOC) :
                new ObjectParameter("TIPODOC", typeof(string));
    
            var nO_DOCParameter = nO_DOC != null ?
                new ObjectParameter("NO_DOC", nO_DOC) :
                new ObjectParameter("NO_DOC", typeof(string));
    
            var rEFERENCIAParameter = rEFERENCIA != null ?
                new ObjectParameter("REFERENCIA", rEFERENCIA) :
                new ObjectParameter("REFERENCIA", typeof(string));
    
            var cONTROLParameter = cONTROL != null ?
                new ObjectParameter("CONTROL", cONTROL) :
                new ObjectParameter("CONTROL", typeof(string));
    
            var cHEQUEParameter = cHEQUE != null ?
                new ObjectParameter("CHEQUE", cHEQUE) :
                new ObjectParameter("CHEQUE", typeof(string));
    
            var cUENTAParameter = cUENTA != null ?
                new ObjectParameter("CUENTA", cUENTA) :
                new ObjectParameter("CUENTA", typeof(string));
    
            var bANCOParameter = bANCO != null ?
                new ObjectParameter("BANCO", bANCO) :
                new ObjectParameter("BANCO", typeof(string));
    
            var cARGOParameter = cARGO.HasValue ?
                new ObjectParameter("CARGO", cARGO) :
                new ObjectParameter("CARGO", typeof(decimal));
    
            var aBONOParameter = aBONO.HasValue ?
                new ObjectParameter("ABONO", aBONO) :
                new ObjectParameter("ABONO", typeof(decimal));
    
            var sALDOParameter = sALDO.HasValue ?
                new ObjectParameter("SALDO", sALDO) :
                new ObjectParameter("SALDO", typeof(decimal));
    
            var fECHAVENCIMIENTOParameter = fECHAVENCIMIENTO.HasValue ?
                new ObjectParameter("FECHAVENCIMIENTO", fECHAVENCIMIENTO) :
                new ObjectParameter("FECHAVENCIMIENTO", typeof(System.DateTime));
    
            var fECHAOPParameter = fECHAOP.HasValue ?
                new ObjectParameter("FECHAOP", fECHAOP) :
                new ObjectParameter("FECHAOP", typeof(System.DateTime));
    
            var fECHAFACTURAParameter = fECHAFACTURA.HasValue ?
                new ObjectParameter("FECHAFACTURA", fECHAFACTURA) :
                new ObjectParameter("FECHAFACTURA", typeof(System.DateTime));
    
            var iD_USUARIOParameter = iD_USUARIO != null ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(string));
    
            var cONDICIONParameter = cONDICION != null ?
                new ObjectParameter("CONDICION", cONDICION) :
                new ObjectParameter("CONDICION", typeof(string));
    
            var mONEDAParameter = mONEDA.HasValue ?
                new ObjectParameter("MONEDA", mONEDA) :
                new ObjectParameter("MONEDA", typeof(int));
    
            var rATEParameter = rATE.HasValue ?
                new ObjectParameter("RATE", rATE) :
                new ObjectParameter("RATE", typeof(decimal));
    
            var sTATUSParameter = sTATUS != null ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(string));
    
            var oBSERVACIONESParameter = oBSERVACIONES != null ?
                new ObjectParameter("OBSERVACIONES", oBSERVACIONES) :
                new ObjectParameter("OBSERVACIONES", typeof(string));
    
            var dEPARTAMENTOParameter = dEPARTAMENTO != null ?
                new ObjectParameter("DEPARTAMENTO", dEPARTAMENTO) :
                new ObjectParameter("DEPARTAMENTO", typeof(string));
    
            var gRUPOParameter = gRUPO != null ?
                new ObjectParameter("GRUPO", gRUPO) :
                new ObjectParameter("GRUPO", typeof(string));
    
            var cONCEPTOParameter = cONCEPTO != null ?
                new ObjectParameter("CONCEPTO", cONCEPTO) :
                new ObjectParameter("CONCEPTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_ACTUALIZACXP", iD_OPParameter, iD_TIENDAParameter, iD_PROVEEDORParameter, tIPODOCParameter, nO_DOCParameter, rEFERENCIAParameter, cONTROLParameter, cHEQUEParameter, cUENTAParameter, bANCOParameter, cARGOParameter, aBONOParameter, sALDOParameter, fECHAVENCIMIENTOParameter, fECHAOPParameter, fECHAFACTURAParameter, iD_USUARIOParameter, cONDICIONParameter, mONEDAParameter, rATEParameter, sTATUSParameter, oBSERVACIONESParameter, dEPARTAMENTOParameter, gRUPOParameter, cONCEPTOParameter);
        }
    
        public virtual int CSP_ACTUALIZACXPCHOF(string iD_OP, string iD_TIENDA, string iD_PROVEEDOR, string tIPODOC, string nO_DOC, string rEFERENCIA, string cONTROL, string cHEQUE, string cUENTA, string bANCO, Nullable<decimal> cARGO, Nullable<decimal> aBONO, Nullable<decimal> sALDO, Nullable<System.DateTime> fECHAVENCIMIENTO, Nullable<System.DateTime> fECHAOP, Nullable<System.DateTime> fECHAFACTURA, string iD_USUARIO, string cONDICION, Nullable<int> mONEDA, Nullable<decimal> rATE, string sTATUS, string oBSERVACIONES)
        {
            var iD_OPParameter = iD_OP != null ?
                new ObjectParameter("ID_OP", iD_OP) :
                new ObjectParameter("ID_OP", typeof(string));
    
            var iD_TIENDAParameter = iD_TIENDA != null ?
                new ObjectParameter("ID_TIENDA", iD_TIENDA) :
                new ObjectParameter("ID_TIENDA", typeof(string));
    
            var iD_PROVEEDORParameter = iD_PROVEEDOR != null ?
                new ObjectParameter("ID_PROVEEDOR", iD_PROVEEDOR) :
                new ObjectParameter("ID_PROVEEDOR", typeof(string));
    
            var tIPODOCParameter = tIPODOC != null ?
                new ObjectParameter("TIPODOC", tIPODOC) :
                new ObjectParameter("TIPODOC", typeof(string));
    
            var nO_DOCParameter = nO_DOC != null ?
                new ObjectParameter("NO_DOC", nO_DOC) :
                new ObjectParameter("NO_DOC", typeof(string));
    
            var rEFERENCIAParameter = rEFERENCIA != null ?
                new ObjectParameter("REFERENCIA", rEFERENCIA) :
                new ObjectParameter("REFERENCIA", typeof(string));
    
            var cONTROLParameter = cONTROL != null ?
                new ObjectParameter("CONTROL", cONTROL) :
                new ObjectParameter("CONTROL", typeof(string));
    
            var cHEQUEParameter = cHEQUE != null ?
                new ObjectParameter("CHEQUE", cHEQUE) :
                new ObjectParameter("CHEQUE", typeof(string));
    
            var cUENTAParameter = cUENTA != null ?
                new ObjectParameter("CUENTA", cUENTA) :
                new ObjectParameter("CUENTA", typeof(string));
    
            var bANCOParameter = bANCO != null ?
                new ObjectParameter("BANCO", bANCO) :
                new ObjectParameter("BANCO", typeof(string));
    
            var cARGOParameter = cARGO.HasValue ?
                new ObjectParameter("CARGO", cARGO) :
                new ObjectParameter("CARGO", typeof(decimal));
    
            var aBONOParameter = aBONO.HasValue ?
                new ObjectParameter("ABONO", aBONO) :
                new ObjectParameter("ABONO", typeof(decimal));
    
            var sALDOParameter = sALDO.HasValue ?
                new ObjectParameter("SALDO", sALDO) :
                new ObjectParameter("SALDO", typeof(decimal));
    
            var fECHAVENCIMIENTOParameter = fECHAVENCIMIENTO.HasValue ?
                new ObjectParameter("FECHAVENCIMIENTO", fECHAVENCIMIENTO) :
                new ObjectParameter("FECHAVENCIMIENTO", typeof(System.DateTime));
    
            var fECHAOPParameter = fECHAOP.HasValue ?
                new ObjectParameter("FECHAOP", fECHAOP) :
                new ObjectParameter("FECHAOP", typeof(System.DateTime));
    
            var fECHAFACTURAParameter = fECHAFACTURA.HasValue ?
                new ObjectParameter("FECHAFACTURA", fECHAFACTURA) :
                new ObjectParameter("FECHAFACTURA", typeof(System.DateTime));
    
            var iD_USUARIOParameter = iD_USUARIO != null ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(string));
    
            var cONDICIONParameter = cONDICION != null ?
                new ObjectParameter("CONDICION", cONDICION) :
                new ObjectParameter("CONDICION", typeof(string));
    
            var mONEDAParameter = mONEDA.HasValue ?
                new ObjectParameter("MONEDA", mONEDA) :
                new ObjectParameter("MONEDA", typeof(int));
    
            var rATEParameter = rATE.HasValue ?
                new ObjectParameter("RATE", rATE) :
                new ObjectParameter("RATE", typeof(decimal));
    
            var sTATUSParameter = sTATUS != null ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(string));
    
            var oBSERVACIONESParameter = oBSERVACIONES != null ?
                new ObjectParameter("OBSERVACIONES", oBSERVACIONES) :
                new ObjectParameter("OBSERVACIONES", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_ACTUALIZACXPCHOF", iD_OPParameter, iD_TIENDAParameter, iD_PROVEEDORParameter, tIPODOCParameter, nO_DOCParameter, rEFERENCIAParameter, cONTROLParameter, cHEQUEParameter, cUENTAParameter, bANCOParameter, cARGOParameter, aBONOParameter, sALDOParameter, fECHAVENCIMIENTOParameter, fECHAOPParameter, fECHAFACTURAParameter, iD_USUARIOParameter, cONDICIONParameter, mONEDAParameter, rATEParameter, sTATUSParameter, oBSERVACIONESParameter);
        }
    
        public virtual int CSP_ACTUALIZACXPSOC(string iD_OP, string iD_TIENDA, string iD_PROVEEDOR, string tIPODOC, string nO_DOC, string rEFERENCIA, string cONTROL, string cHEQUE, string cUENTA, string bANCO, Nullable<decimal> cARGO, Nullable<decimal> aBONO, Nullable<decimal> sALDO, Nullable<System.DateTime> fECHAVENCIMIENTO, Nullable<System.DateTime> fECHAOP, Nullable<System.DateTime> fECHAFACTURA, string iD_USUARIO, string cONDICION, Nullable<int> mONEDA, Nullable<decimal> rATE, string sTATUS, string oBSERVACIONES)
        {
            var iD_OPParameter = iD_OP != null ?
                new ObjectParameter("ID_OP", iD_OP) :
                new ObjectParameter("ID_OP", typeof(string));
    
            var iD_TIENDAParameter = iD_TIENDA != null ?
                new ObjectParameter("ID_TIENDA", iD_TIENDA) :
                new ObjectParameter("ID_TIENDA", typeof(string));
    
            var iD_PROVEEDORParameter = iD_PROVEEDOR != null ?
                new ObjectParameter("ID_PROVEEDOR", iD_PROVEEDOR) :
                new ObjectParameter("ID_PROVEEDOR", typeof(string));
    
            var tIPODOCParameter = tIPODOC != null ?
                new ObjectParameter("TIPODOC", tIPODOC) :
                new ObjectParameter("TIPODOC", typeof(string));
    
            var nO_DOCParameter = nO_DOC != null ?
                new ObjectParameter("NO_DOC", nO_DOC) :
                new ObjectParameter("NO_DOC", typeof(string));
    
            var rEFERENCIAParameter = rEFERENCIA != null ?
                new ObjectParameter("REFERENCIA", rEFERENCIA) :
                new ObjectParameter("REFERENCIA", typeof(string));
    
            var cONTROLParameter = cONTROL != null ?
                new ObjectParameter("CONTROL", cONTROL) :
                new ObjectParameter("CONTROL", typeof(string));
    
            var cHEQUEParameter = cHEQUE != null ?
                new ObjectParameter("CHEQUE", cHEQUE) :
                new ObjectParameter("CHEQUE", typeof(string));
    
            var cUENTAParameter = cUENTA != null ?
                new ObjectParameter("CUENTA", cUENTA) :
                new ObjectParameter("CUENTA", typeof(string));
    
            var bANCOParameter = bANCO != null ?
                new ObjectParameter("BANCO", bANCO) :
                new ObjectParameter("BANCO", typeof(string));
    
            var cARGOParameter = cARGO.HasValue ?
                new ObjectParameter("CARGO", cARGO) :
                new ObjectParameter("CARGO", typeof(decimal));
    
            var aBONOParameter = aBONO.HasValue ?
                new ObjectParameter("ABONO", aBONO) :
                new ObjectParameter("ABONO", typeof(decimal));
    
            var sALDOParameter = sALDO.HasValue ?
                new ObjectParameter("SALDO", sALDO) :
                new ObjectParameter("SALDO", typeof(decimal));
    
            var fECHAVENCIMIENTOParameter = fECHAVENCIMIENTO.HasValue ?
                new ObjectParameter("FECHAVENCIMIENTO", fECHAVENCIMIENTO) :
                new ObjectParameter("FECHAVENCIMIENTO", typeof(System.DateTime));
    
            var fECHAOPParameter = fECHAOP.HasValue ?
                new ObjectParameter("FECHAOP", fECHAOP) :
                new ObjectParameter("FECHAOP", typeof(System.DateTime));
    
            var fECHAFACTURAParameter = fECHAFACTURA.HasValue ?
                new ObjectParameter("FECHAFACTURA", fECHAFACTURA) :
                new ObjectParameter("FECHAFACTURA", typeof(System.DateTime));
    
            var iD_USUARIOParameter = iD_USUARIO != null ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(string));
    
            var cONDICIONParameter = cONDICION != null ?
                new ObjectParameter("CONDICION", cONDICION) :
                new ObjectParameter("CONDICION", typeof(string));
    
            var mONEDAParameter = mONEDA.HasValue ?
                new ObjectParameter("MONEDA", mONEDA) :
                new ObjectParameter("MONEDA", typeof(int));
    
            var rATEParameter = rATE.HasValue ?
                new ObjectParameter("RATE", rATE) :
                new ObjectParameter("RATE", typeof(decimal));
    
            var sTATUSParameter = sTATUS != null ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(string));
    
            var oBSERVACIONESParameter = oBSERVACIONES != null ?
                new ObjectParameter("OBSERVACIONES", oBSERVACIONES) :
                new ObjectParameter("OBSERVACIONES", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_ACTUALIZACXPSOC", iD_OPParameter, iD_TIENDAParameter, iD_PROVEEDORParameter, tIPODOCParameter, nO_DOCParameter, rEFERENCIAParameter, cONTROLParameter, cHEQUEParameter, cUENTAParameter, bANCOParameter, cARGOParameter, aBONOParameter, sALDOParameter, fECHAVENCIMIENTOParameter, fECHAOPParameter, fECHAFACTURAParameter, iD_USUARIOParameter, cONDICIONParameter, mONEDAParameter, rATEParameter, sTATUSParameter, oBSERVACIONESParameter);
        }
    
        public virtual int CSP_ACTUALIZAINVE(string iD_PRODUCTO, Nullable<decimal> cANTIDAD, Nullable<byte> tIPOACT, string fECHAEDIT, string iD_USUARIOEDIT)
        {
            var iD_PRODUCTOParameter = iD_PRODUCTO != null ?
                new ObjectParameter("ID_PRODUCTO", iD_PRODUCTO) :
                new ObjectParameter("ID_PRODUCTO", typeof(string));
    
            var cANTIDADParameter = cANTIDAD.HasValue ?
                new ObjectParameter("CANTIDAD", cANTIDAD) :
                new ObjectParameter("CANTIDAD", typeof(decimal));
    
            var tIPOACTParameter = tIPOACT.HasValue ?
                new ObjectParameter("TIPOACT", tIPOACT) :
                new ObjectParameter("TIPOACT", typeof(byte));
    
            var fECHAEDITParameter = fECHAEDIT != null ?
                new ObjectParameter("FECHAEDIT", fECHAEDIT) :
                new ObjectParameter("FECHAEDIT", typeof(string));
    
            var iD_USUARIOEDITParameter = iD_USUARIOEDIT != null ?
                new ObjectParameter("ID_USUARIOEDIT", iD_USUARIOEDIT) :
                new ObjectParameter("ID_USUARIOEDIT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_ACTUALIZAINVE", iD_PRODUCTOParameter, cANTIDADParameter, tIPOACTParameter, fECHAEDITParameter, iD_USUARIOEDITParameter);
        }
    
        public virtual int CSP_ACTUALIZAUSUARIOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_ACTUALIZAUSUARIOS");
        }
    
        public virtual int CSP_REGISTRACOBRO(string iD_OP, Nullable<decimal> tIPOCAMBIO, Nullable<decimal> iMPORTE, Nullable<decimal> rECIBIDO, Nullable<decimal> cAMBIO, string fECHAOP, string fECHAEDIT, string oBSCOBROS)
        {
            var iD_OPParameter = iD_OP != null ?
                new ObjectParameter("ID_OP", iD_OP) :
                new ObjectParameter("ID_OP", typeof(string));
    
            var tIPOCAMBIOParameter = tIPOCAMBIO.HasValue ?
                new ObjectParameter("TIPOCAMBIO", tIPOCAMBIO) :
                new ObjectParameter("TIPOCAMBIO", typeof(decimal));
    
            var iMPORTEParameter = iMPORTE.HasValue ?
                new ObjectParameter("IMPORTE", iMPORTE) :
                new ObjectParameter("IMPORTE", typeof(decimal));
    
            var rECIBIDOParameter = rECIBIDO.HasValue ?
                new ObjectParameter("RECIBIDO", rECIBIDO) :
                new ObjectParameter("RECIBIDO", typeof(decimal));
    
            var cAMBIOParameter = cAMBIO.HasValue ?
                new ObjectParameter("CAMBIO", cAMBIO) :
                new ObjectParameter("CAMBIO", typeof(decimal));
    
            var fECHAOPParameter = fECHAOP != null ?
                new ObjectParameter("FECHAOP", fECHAOP) :
                new ObjectParameter("FECHAOP", typeof(string));
    
            var fECHAEDITParameter = fECHAEDIT != null ?
                new ObjectParameter("FECHAEDIT", fECHAEDIT) :
                new ObjectParameter("FECHAEDIT", typeof(string));
    
            var oBSCOBROSParameter = oBSCOBROS != null ?
                new ObjectParameter("OBSCOBROS", oBSCOBROS) :
                new ObjectParameter("OBSCOBROS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_REGISTRACOBRO", iD_OPParameter, tIPOCAMBIOParameter, iMPORTEParameter, rECIBIDOParameter, cAMBIOParameter, fECHAOPParameter, fECHAEDITParameter, oBSCOBROSParameter);
        }
    
        public virtual int CSP_REGISTRACOBRODET(string iD_OP, string iD_FORMAPAGO, string rEFERENCIA, Nullable<decimal> cANT, string dESCRIPCION, Nullable<bool> dIVISA, Nullable<decimal> tIPOCAM, Nullable<decimal> iMPORTE)
        {
            var iD_OPParameter = iD_OP != null ?
                new ObjectParameter("ID_OP", iD_OP) :
                new ObjectParameter("ID_OP", typeof(string));
    
            var iD_FORMAPAGOParameter = iD_FORMAPAGO != null ?
                new ObjectParameter("ID_FORMAPAGO", iD_FORMAPAGO) :
                new ObjectParameter("ID_FORMAPAGO", typeof(string));
    
            var rEFERENCIAParameter = rEFERENCIA != null ?
                new ObjectParameter("REFERENCIA", rEFERENCIA) :
                new ObjectParameter("REFERENCIA", typeof(string));
    
            var cANTParameter = cANT.HasValue ?
                new ObjectParameter("CANT", cANT) :
                new ObjectParameter("CANT", typeof(decimal));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var dIVISAParameter = dIVISA.HasValue ?
                new ObjectParameter("DIVISA", dIVISA) :
                new ObjectParameter("DIVISA", typeof(bool));
    
            var tIPOCAMParameter = tIPOCAM.HasValue ?
                new ObjectParameter("TIPOCAM", tIPOCAM) :
                new ObjectParameter("TIPOCAM", typeof(decimal));
    
            var iMPORTEParameter = iMPORTE.HasValue ?
                new ObjectParameter("IMPORTE", iMPORTE) :
                new ObjectParameter("IMPORTE", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_REGISTRACOBRODET", iD_OPParameter, iD_FORMAPAGOParameter, rEFERENCIAParameter, cANTParameter, dESCRIPCIONParameter, dIVISAParameter, tIPOCAMParameter, iMPORTEParameter);
        }
    
        public virtual int CSP_REGISTRACOMPRA(string iD_TIENDA, string iD_OP, string iD_PROVEEDOR, Nullable<decimal> rATE, string nO_DOC, string rEFERENCIA, string cONCEPTO, Nullable<System.DateTime> fECHAFACTURA, Nullable<System.DateTime> fECHARECEPCION, Nullable<System.DateTime> fECHAVENCIMIENTO, string cONDICION, string sTATUS, Nullable<decimal> iMPORTE, Nullable<decimal> dESPORCEN, Nullable<decimal> dESCIMP, Nullable<decimal> sUBTOTAL, Nullable<decimal> iVA, Nullable<decimal> tOTAL, string iD_USUARIO, Nullable<System.DateTime> fECHAOP, Nullable<System.DateTime> fECHAEDIT, string iD_USUARIOEDIT, Nullable<bool> dESGLOCEIVA, Nullable<bool> iNDIRECTOS, Nullable<decimal> iNDIRECOSIMP)
        {
            var iD_TIENDAParameter = iD_TIENDA != null ?
                new ObjectParameter("ID_TIENDA", iD_TIENDA) :
                new ObjectParameter("ID_TIENDA", typeof(string));
    
            var iD_OPParameter = iD_OP != null ?
                new ObjectParameter("ID_OP", iD_OP) :
                new ObjectParameter("ID_OP", typeof(string));
    
            var iD_PROVEEDORParameter = iD_PROVEEDOR != null ?
                new ObjectParameter("ID_PROVEEDOR", iD_PROVEEDOR) :
                new ObjectParameter("ID_PROVEEDOR", typeof(string));
    
            var rATEParameter = rATE.HasValue ?
                new ObjectParameter("RATE", rATE) :
                new ObjectParameter("RATE", typeof(decimal));
    
            var nO_DOCParameter = nO_DOC != null ?
                new ObjectParameter("NO_DOC", nO_DOC) :
                new ObjectParameter("NO_DOC", typeof(string));
    
            var rEFERENCIAParameter = rEFERENCIA != null ?
                new ObjectParameter("REFERENCIA", rEFERENCIA) :
                new ObjectParameter("REFERENCIA", typeof(string));
    
            var cONCEPTOParameter = cONCEPTO != null ?
                new ObjectParameter("CONCEPTO", cONCEPTO) :
                new ObjectParameter("CONCEPTO", typeof(string));
    
            var fECHAFACTURAParameter = fECHAFACTURA.HasValue ?
                new ObjectParameter("FECHAFACTURA", fECHAFACTURA) :
                new ObjectParameter("FECHAFACTURA", typeof(System.DateTime));
    
            var fECHARECEPCIONParameter = fECHARECEPCION.HasValue ?
                new ObjectParameter("FECHARECEPCION", fECHARECEPCION) :
                new ObjectParameter("FECHARECEPCION", typeof(System.DateTime));
    
            var fECHAVENCIMIENTOParameter = fECHAVENCIMIENTO.HasValue ?
                new ObjectParameter("FECHAVENCIMIENTO", fECHAVENCIMIENTO) :
                new ObjectParameter("FECHAVENCIMIENTO", typeof(System.DateTime));
    
            var cONDICIONParameter = cONDICION != null ?
                new ObjectParameter("CONDICION", cONDICION) :
                new ObjectParameter("CONDICION", typeof(string));
    
            var sTATUSParameter = sTATUS != null ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(string));
    
            var iMPORTEParameter = iMPORTE.HasValue ?
                new ObjectParameter("IMPORTE", iMPORTE) :
                new ObjectParameter("IMPORTE", typeof(decimal));
    
            var dESPORCENParameter = dESPORCEN.HasValue ?
                new ObjectParameter("DESPORCEN", dESPORCEN) :
                new ObjectParameter("DESPORCEN", typeof(decimal));
    
            var dESCIMPParameter = dESCIMP.HasValue ?
                new ObjectParameter("DESCIMP", dESCIMP) :
                new ObjectParameter("DESCIMP", typeof(decimal));
    
            var sUBTOTALParameter = sUBTOTAL.HasValue ?
                new ObjectParameter("SUBTOTAL", sUBTOTAL) :
                new ObjectParameter("SUBTOTAL", typeof(decimal));
    
            var iVAParameter = iVA.HasValue ?
                new ObjectParameter("IVA", iVA) :
                new ObjectParameter("IVA", typeof(decimal));
    
            var tOTALParameter = tOTAL.HasValue ?
                new ObjectParameter("TOTAL", tOTAL) :
                new ObjectParameter("TOTAL", typeof(decimal));
    
            var iD_USUARIOParameter = iD_USUARIO != null ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(string));
    
            var fECHAOPParameter = fECHAOP.HasValue ?
                new ObjectParameter("FECHAOP", fECHAOP) :
                new ObjectParameter("FECHAOP", typeof(System.DateTime));
    
            var fECHAEDITParameter = fECHAEDIT.HasValue ?
                new ObjectParameter("FECHAEDIT", fECHAEDIT) :
                new ObjectParameter("FECHAEDIT", typeof(System.DateTime));
    
            var iD_USUARIOEDITParameter = iD_USUARIOEDIT != null ?
                new ObjectParameter("ID_USUARIOEDIT", iD_USUARIOEDIT) :
                new ObjectParameter("ID_USUARIOEDIT", typeof(string));
    
            var dESGLOCEIVAParameter = dESGLOCEIVA.HasValue ?
                new ObjectParameter("DESGLOCEIVA", dESGLOCEIVA) :
                new ObjectParameter("DESGLOCEIVA", typeof(bool));
    
            var iNDIRECTOSParameter = iNDIRECTOS.HasValue ?
                new ObjectParameter("INDIRECTOS", iNDIRECTOS) :
                new ObjectParameter("INDIRECTOS", typeof(bool));
    
            var iNDIRECOSIMPParameter = iNDIRECOSIMP.HasValue ?
                new ObjectParameter("INDIRECOSIMP", iNDIRECOSIMP) :
                new ObjectParameter("INDIRECOSIMP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_REGISTRACOMPRA", iD_TIENDAParameter, iD_OPParameter, iD_PROVEEDORParameter, rATEParameter, nO_DOCParameter, rEFERENCIAParameter, cONCEPTOParameter, fECHAFACTURAParameter, fECHARECEPCIONParameter, fECHAVENCIMIENTOParameter, cONDICIONParameter, sTATUSParameter, iMPORTEParameter, dESPORCENParameter, dESCIMPParameter, sUBTOTALParameter, iVAParameter, tOTALParameter, iD_USUARIOParameter, fECHAOPParameter, fECHAEDITParameter, iD_USUARIOEDITParameter, dESGLOCEIVAParameter, iNDIRECTOSParameter, iNDIRECOSIMPParameter);
        }
    
        public virtual int CSP_REGISTRACOMPRADET(string iD_OP, string iD_PRODUCTO, string iD_PROVEEDOR, string dESCRIPCION, Nullable<int> cANT, Nullable<decimal> pRECIO_LISTA, Nullable<decimal> dESCPORC, Nullable<decimal> dESCIMP, Nullable<decimal> pRECIO, Nullable<decimal> iMPORTE, Nullable<decimal> pORCIVA, Nullable<decimal> iVA, Nullable<decimal> iNDIRECTO, Nullable<decimal> cOSTONETO, Nullable<decimal> cOSTOPROMEDIO, Nullable<bool> aCTUALIZAINVE, Nullable<decimal> iMPORTECOSTOPROMEDIO)
        {
            var iD_OPParameter = iD_OP != null ?
                new ObjectParameter("ID_OP", iD_OP) :
                new ObjectParameter("ID_OP", typeof(string));
    
            var iD_PRODUCTOParameter = iD_PRODUCTO != null ?
                new ObjectParameter("ID_PRODUCTO", iD_PRODUCTO) :
                new ObjectParameter("ID_PRODUCTO", typeof(string));
    
            var iD_PROVEEDORParameter = iD_PROVEEDOR != null ?
                new ObjectParameter("ID_PROVEEDOR", iD_PROVEEDOR) :
                new ObjectParameter("ID_PROVEEDOR", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var cANTParameter = cANT.HasValue ?
                new ObjectParameter("CANT", cANT) :
                new ObjectParameter("CANT", typeof(int));
    
            var pRECIO_LISTAParameter = pRECIO_LISTA.HasValue ?
                new ObjectParameter("PRECIO_LISTA", pRECIO_LISTA) :
                new ObjectParameter("PRECIO_LISTA", typeof(decimal));
    
            var dESCPORCParameter = dESCPORC.HasValue ?
                new ObjectParameter("DESCPORC", dESCPORC) :
                new ObjectParameter("DESCPORC", typeof(decimal));
    
            var dESCIMPParameter = dESCIMP.HasValue ?
                new ObjectParameter("DESCIMP", dESCIMP) :
                new ObjectParameter("DESCIMP", typeof(decimal));
    
            var pRECIOParameter = pRECIO.HasValue ?
                new ObjectParameter("PRECIO", pRECIO) :
                new ObjectParameter("PRECIO", typeof(decimal));
    
            var iMPORTEParameter = iMPORTE.HasValue ?
                new ObjectParameter("IMPORTE", iMPORTE) :
                new ObjectParameter("IMPORTE", typeof(decimal));
    
            var pORCIVAParameter = pORCIVA.HasValue ?
                new ObjectParameter("PORCIVA", pORCIVA) :
                new ObjectParameter("PORCIVA", typeof(decimal));
    
            var iVAParameter = iVA.HasValue ?
                new ObjectParameter("IVA", iVA) :
                new ObjectParameter("IVA", typeof(decimal));
    
            var iNDIRECTOParameter = iNDIRECTO.HasValue ?
                new ObjectParameter("INDIRECTO", iNDIRECTO) :
                new ObjectParameter("INDIRECTO", typeof(decimal));
    
            var cOSTONETOParameter = cOSTONETO.HasValue ?
                new ObjectParameter("COSTONETO", cOSTONETO) :
                new ObjectParameter("COSTONETO", typeof(decimal));
    
            var cOSTOPROMEDIOParameter = cOSTOPROMEDIO.HasValue ?
                new ObjectParameter("COSTOPROMEDIO", cOSTOPROMEDIO) :
                new ObjectParameter("COSTOPROMEDIO", typeof(decimal));
    
            var aCTUALIZAINVEParameter = aCTUALIZAINVE.HasValue ?
                new ObjectParameter("ACTUALIZAINVE", aCTUALIZAINVE) :
                new ObjectParameter("ACTUALIZAINVE", typeof(bool));
    
            var iMPORTECOSTOPROMEDIOParameter = iMPORTECOSTOPROMEDIO.HasValue ?
                new ObjectParameter("IMPORTECOSTOPROMEDIO", iMPORTECOSTOPROMEDIO) :
                new ObjectParameter("IMPORTECOSTOPROMEDIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_REGISTRACOMPRADET", iD_OPParameter, iD_PRODUCTOParameter, iD_PROVEEDORParameter, dESCRIPCIONParameter, cANTParameter, pRECIO_LISTAParameter, dESCPORCParameter, dESCIMPParameter, pRECIOParameter, iMPORTEParameter, pORCIVAParameter, iVAParameter, iNDIRECTOParameter, cOSTONETOParameter, cOSTOPROMEDIOParameter, aCTUALIZAINVEParameter, iMPORTECOSTOPROMEDIOParameter);
        }
    
        public virtual int CSP_REGISTRAFACTURA(string iD_TIENDA, string iD_OP, string iD_PROVEEDOR, Nullable<decimal> rATE, string nO_DOC, string rEFERENCIA, string cONCEPTO, Nullable<System.DateTime> fECHAFACTURA, Nullable<System.DateTime> fECHARECEPCION, Nullable<System.DateTime> fECHAVENCIMIENTO, string cONDICION, string sTATUS, Nullable<decimal> iMPORTE, Nullable<decimal> dESPORCEN, Nullable<decimal> dESCIMP, Nullable<decimal> sUBTOTAL, Nullable<decimal> iVA, Nullable<decimal> tOTAL, string iD_USUARIO, Nullable<System.DateTime> fECHAOP, Nullable<System.DateTime> fECHAEDIT, string iD_USUARIOEDIT, Nullable<bool> dESGLOCEIVA, Nullable<bool> iNDIRECTOS, Nullable<decimal> iNDIRECOSIMP)
        {
            var iD_TIENDAParameter = iD_TIENDA != null ?
                new ObjectParameter("ID_TIENDA", iD_TIENDA) :
                new ObjectParameter("ID_TIENDA", typeof(string));
    
            var iD_OPParameter = iD_OP != null ?
                new ObjectParameter("ID_OP", iD_OP) :
                new ObjectParameter("ID_OP", typeof(string));
    
            var iD_PROVEEDORParameter = iD_PROVEEDOR != null ?
                new ObjectParameter("ID_PROVEEDOR", iD_PROVEEDOR) :
                new ObjectParameter("ID_PROVEEDOR", typeof(string));
    
            var rATEParameter = rATE.HasValue ?
                new ObjectParameter("RATE", rATE) :
                new ObjectParameter("RATE", typeof(decimal));
    
            var nO_DOCParameter = nO_DOC != null ?
                new ObjectParameter("NO_DOC", nO_DOC) :
                new ObjectParameter("NO_DOC", typeof(string));
    
            var rEFERENCIAParameter = rEFERENCIA != null ?
                new ObjectParameter("REFERENCIA", rEFERENCIA) :
                new ObjectParameter("REFERENCIA", typeof(string));
    
            var cONCEPTOParameter = cONCEPTO != null ?
                new ObjectParameter("CONCEPTO", cONCEPTO) :
                new ObjectParameter("CONCEPTO", typeof(string));
    
            var fECHAFACTURAParameter = fECHAFACTURA.HasValue ?
                new ObjectParameter("FECHAFACTURA", fECHAFACTURA) :
                new ObjectParameter("FECHAFACTURA", typeof(System.DateTime));
    
            var fECHARECEPCIONParameter = fECHARECEPCION.HasValue ?
                new ObjectParameter("FECHARECEPCION", fECHARECEPCION) :
                new ObjectParameter("FECHARECEPCION", typeof(System.DateTime));
    
            var fECHAVENCIMIENTOParameter = fECHAVENCIMIENTO.HasValue ?
                new ObjectParameter("FECHAVENCIMIENTO", fECHAVENCIMIENTO) :
                new ObjectParameter("FECHAVENCIMIENTO", typeof(System.DateTime));
    
            var cONDICIONParameter = cONDICION != null ?
                new ObjectParameter("CONDICION", cONDICION) :
                new ObjectParameter("CONDICION", typeof(string));
    
            var sTATUSParameter = sTATUS != null ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(string));
    
            var iMPORTEParameter = iMPORTE.HasValue ?
                new ObjectParameter("IMPORTE", iMPORTE) :
                new ObjectParameter("IMPORTE", typeof(decimal));
    
            var dESPORCENParameter = dESPORCEN.HasValue ?
                new ObjectParameter("DESPORCEN", dESPORCEN) :
                new ObjectParameter("DESPORCEN", typeof(decimal));
    
            var dESCIMPParameter = dESCIMP.HasValue ?
                new ObjectParameter("DESCIMP", dESCIMP) :
                new ObjectParameter("DESCIMP", typeof(decimal));
    
            var sUBTOTALParameter = sUBTOTAL.HasValue ?
                new ObjectParameter("SUBTOTAL", sUBTOTAL) :
                new ObjectParameter("SUBTOTAL", typeof(decimal));
    
            var iVAParameter = iVA.HasValue ?
                new ObjectParameter("IVA", iVA) :
                new ObjectParameter("IVA", typeof(decimal));
    
            var tOTALParameter = tOTAL.HasValue ?
                new ObjectParameter("TOTAL", tOTAL) :
                new ObjectParameter("TOTAL", typeof(decimal));
    
            var iD_USUARIOParameter = iD_USUARIO != null ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(string));
    
            var fECHAOPParameter = fECHAOP.HasValue ?
                new ObjectParameter("FECHAOP", fECHAOP) :
                new ObjectParameter("FECHAOP", typeof(System.DateTime));
    
            var fECHAEDITParameter = fECHAEDIT.HasValue ?
                new ObjectParameter("FECHAEDIT", fECHAEDIT) :
                new ObjectParameter("FECHAEDIT", typeof(System.DateTime));
    
            var iD_USUARIOEDITParameter = iD_USUARIOEDIT != null ?
                new ObjectParameter("ID_USUARIOEDIT", iD_USUARIOEDIT) :
                new ObjectParameter("ID_USUARIOEDIT", typeof(string));
    
            var dESGLOCEIVAParameter = dESGLOCEIVA.HasValue ?
                new ObjectParameter("DESGLOCEIVA", dESGLOCEIVA) :
                new ObjectParameter("DESGLOCEIVA", typeof(bool));
    
            var iNDIRECTOSParameter = iNDIRECTOS.HasValue ?
                new ObjectParameter("INDIRECTOS", iNDIRECTOS) :
                new ObjectParameter("INDIRECTOS", typeof(bool));
    
            var iNDIRECOSIMPParameter = iNDIRECOSIMP.HasValue ?
                new ObjectParameter("INDIRECOSIMP", iNDIRECOSIMP) :
                new ObjectParameter("INDIRECOSIMP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_REGISTRAFACTURA", iD_TIENDAParameter, iD_OPParameter, iD_PROVEEDORParameter, rATEParameter, nO_DOCParameter, rEFERENCIAParameter, cONCEPTOParameter, fECHAFACTURAParameter, fECHARECEPCIONParameter, fECHAVENCIMIENTOParameter, cONDICIONParameter, sTATUSParameter, iMPORTEParameter, dESPORCENParameter, dESCIMPParameter, sUBTOTALParameter, iVAParameter, tOTALParameter, iD_USUARIOParameter, fECHAOPParameter, fECHAEDITParameter, iD_USUARIOEDITParameter, dESGLOCEIVAParameter, iNDIRECTOSParameter, iNDIRECOSIMPParameter);
        }
    
        public virtual int CSP_REGISTRAFACTURADET(string iD_OP, string iD_PRODUCTO, string iD_PROVEEDOR, string dESCRIPCION, Nullable<int> cANT, Nullable<decimal> pRECIO_LISTA, Nullable<decimal> dESCPORC, Nullable<decimal> dESCIMP, Nullable<decimal> pRECIO, Nullable<decimal> iMPORTE, Nullable<decimal> pORCIVA, Nullable<decimal> iVA, Nullable<decimal> iNDIRECTO, Nullable<decimal> cOSTONETO, Nullable<decimal> cOSTOPROMEDIO, Nullable<bool> aCTUALIZAINVE, Nullable<decimal> iMPORTECOSTOPROMEDIO)
        {
            var iD_OPParameter = iD_OP != null ?
                new ObjectParameter("ID_OP", iD_OP) :
                new ObjectParameter("ID_OP", typeof(string));
    
            var iD_PRODUCTOParameter = iD_PRODUCTO != null ?
                new ObjectParameter("ID_PRODUCTO", iD_PRODUCTO) :
                new ObjectParameter("ID_PRODUCTO", typeof(string));
    
            var iD_PROVEEDORParameter = iD_PROVEEDOR != null ?
                new ObjectParameter("ID_PROVEEDOR", iD_PROVEEDOR) :
                new ObjectParameter("ID_PROVEEDOR", typeof(string));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var cANTParameter = cANT.HasValue ?
                new ObjectParameter("CANT", cANT) :
                new ObjectParameter("CANT", typeof(int));
    
            var pRECIO_LISTAParameter = pRECIO_LISTA.HasValue ?
                new ObjectParameter("PRECIO_LISTA", pRECIO_LISTA) :
                new ObjectParameter("PRECIO_LISTA", typeof(decimal));
    
            var dESCPORCParameter = dESCPORC.HasValue ?
                new ObjectParameter("DESCPORC", dESCPORC) :
                new ObjectParameter("DESCPORC", typeof(decimal));
    
            var dESCIMPParameter = dESCIMP.HasValue ?
                new ObjectParameter("DESCIMP", dESCIMP) :
                new ObjectParameter("DESCIMP", typeof(decimal));
    
            var pRECIOParameter = pRECIO.HasValue ?
                new ObjectParameter("PRECIO", pRECIO) :
                new ObjectParameter("PRECIO", typeof(decimal));
    
            var iMPORTEParameter = iMPORTE.HasValue ?
                new ObjectParameter("IMPORTE", iMPORTE) :
                new ObjectParameter("IMPORTE", typeof(decimal));
    
            var pORCIVAParameter = pORCIVA.HasValue ?
                new ObjectParameter("PORCIVA", pORCIVA) :
                new ObjectParameter("PORCIVA", typeof(decimal));
    
            var iVAParameter = iVA.HasValue ?
                new ObjectParameter("IVA", iVA) :
                new ObjectParameter("IVA", typeof(decimal));
    
            var iNDIRECTOParameter = iNDIRECTO.HasValue ?
                new ObjectParameter("INDIRECTO", iNDIRECTO) :
                new ObjectParameter("INDIRECTO", typeof(decimal));
    
            var cOSTONETOParameter = cOSTONETO.HasValue ?
                new ObjectParameter("COSTONETO", cOSTONETO) :
                new ObjectParameter("COSTONETO", typeof(decimal));
    
            var cOSTOPROMEDIOParameter = cOSTOPROMEDIO.HasValue ?
                new ObjectParameter("COSTOPROMEDIO", cOSTOPROMEDIO) :
                new ObjectParameter("COSTOPROMEDIO", typeof(decimal));
    
            var aCTUALIZAINVEParameter = aCTUALIZAINVE.HasValue ?
                new ObjectParameter("ACTUALIZAINVE", aCTUALIZAINVE) :
                new ObjectParameter("ACTUALIZAINVE", typeof(bool));
    
            var iMPORTECOSTOPROMEDIOParameter = iMPORTECOSTOPROMEDIO.HasValue ?
                new ObjectParameter("IMPORTECOSTOPROMEDIO", iMPORTECOSTOPROMEDIO) :
                new ObjectParameter("IMPORTECOSTOPROMEDIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_REGISTRAFACTURADET", iD_OPParameter, iD_PRODUCTOParameter, iD_PROVEEDORParameter, dESCRIPCIONParameter, cANTParameter, pRECIO_LISTAParameter, dESCPORCParameter, dESCIMPParameter, pRECIOParameter, iMPORTEParameter, pORCIVAParameter, iVAParameter, iNDIRECTOParameter, cOSTONETOParameter, cOSTOPROMEDIOParameter, aCTUALIZAINVEParameter, iMPORTECOSTOPROMEDIOParameter);
        }
    
        public virtual int CSP_REGISTRAMOV(string iD_TIENDA, string iD_OP, string iD_MOV, string tIPO, string rEFERENCIA, string eNVIADOA, Nullable<decimal> iMPVENTA, Nullable<decimal> iMPCOSTO, Nullable<System.DateTime> fECHAOP, string iD_USUARIO, string oBSERVACION)
        {
            var iD_TIENDAParameter = iD_TIENDA != null ?
                new ObjectParameter("ID_TIENDA", iD_TIENDA) :
                new ObjectParameter("ID_TIENDA", typeof(string));
    
            var iD_OPParameter = iD_OP != null ?
                new ObjectParameter("ID_OP", iD_OP) :
                new ObjectParameter("ID_OP", typeof(string));
    
            var iD_MOVParameter = iD_MOV != null ?
                new ObjectParameter("ID_MOV", iD_MOV) :
                new ObjectParameter("ID_MOV", typeof(string));
    
            var tIPOParameter = tIPO != null ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(string));
    
            var rEFERENCIAParameter = rEFERENCIA != null ?
                new ObjectParameter("REFERENCIA", rEFERENCIA) :
                new ObjectParameter("REFERENCIA", typeof(string));
    
            var eNVIADOAParameter = eNVIADOA != null ?
                new ObjectParameter("ENVIADOA", eNVIADOA) :
                new ObjectParameter("ENVIADOA", typeof(string));
    
            var iMPVENTAParameter = iMPVENTA.HasValue ?
                new ObjectParameter("IMPVENTA", iMPVENTA) :
                new ObjectParameter("IMPVENTA", typeof(decimal));
    
            var iMPCOSTOParameter = iMPCOSTO.HasValue ?
                new ObjectParameter("IMPCOSTO", iMPCOSTO) :
                new ObjectParameter("IMPCOSTO", typeof(decimal));
    
            var fECHAOPParameter = fECHAOP.HasValue ?
                new ObjectParameter("FECHAOP", fECHAOP) :
                new ObjectParameter("FECHAOP", typeof(System.DateTime));
    
            var iD_USUARIOParameter = iD_USUARIO != null ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(string));
    
            var oBSERVACIONParameter = oBSERVACION != null ?
                new ObjectParameter("OBSERVACION", oBSERVACION) :
                new ObjectParameter("OBSERVACION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_REGISTRAMOV", iD_TIENDAParameter, iD_OPParameter, iD_MOVParameter, tIPOParameter, rEFERENCIAParameter, eNVIADOAParameter, iMPVENTAParameter, iMPCOSTOParameter, fECHAOPParameter, iD_USUARIOParameter, oBSERVACIONParameter);
        }
    
        public virtual int CSP_REGISTRAMOVDET(string iD_PRODUCTO, string iD_OP, Nullable<decimal> eNTRADA, Nullable<decimal> sALIDA, Nullable<decimal> vENTA, Nullable<decimal> cOSTO, Nullable<decimal> cOSTOUNI, Nullable<bool> aCTUALIZAINVE, string iD_MOV)
        {
            var iD_PRODUCTOParameter = iD_PRODUCTO != null ?
                new ObjectParameter("ID_PRODUCTO", iD_PRODUCTO) :
                new ObjectParameter("ID_PRODUCTO", typeof(string));
    
            var iD_OPParameter = iD_OP != null ?
                new ObjectParameter("ID_OP", iD_OP) :
                new ObjectParameter("ID_OP", typeof(string));
    
            var eNTRADAParameter = eNTRADA.HasValue ?
                new ObjectParameter("ENTRADA", eNTRADA) :
                new ObjectParameter("ENTRADA", typeof(decimal));
    
            var sALIDAParameter = sALIDA.HasValue ?
                new ObjectParameter("SALIDA", sALIDA) :
                new ObjectParameter("SALIDA", typeof(decimal));
    
            var vENTAParameter = vENTA.HasValue ?
                new ObjectParameter("VENTA", vENTA) :
                new ObjectParameter("VENTA", typeof(decimal));
    
            var cOSTOParameter = cOSTO.HasValue ?
                new ObjectParameter("COSTO", cOSTO) :
                new ObjectParameter("COSTO", typeof(decimal));
    
            var cOSTOUNIParameter = cOSTOUNI.HasValue ?
                new ObjectParameter("COSTOUNI", cOSTOUNI) :
                new ObjectParameter("COSTOUNI", typeof(decimal));
    
            var aCTUALIZAINVEParameter = aCTUALIZAINVE.HasValue ?
                new ObjectParameter("ACTUALIZAINVE", aCTUALIZAINVE) :
                new ObjectParameter("ACTUALIZAINVE", typeof(bool));
    
            var iD_MOVParameter = iD_MOV != null ?
                new ObjectParameter("ID_MOV", iD_MOV) :
                new ObjectParameter("ID_MOV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_REGISTRAMOVDET", iD_PRODUCTOParameter, iD_OPParameter, eNTRADAParameter, sALIDAParameter, vENTAParameter, cOSTOParameter, cOSTOUNIParameter, aCTUALIZAINVEParameter, iD_MOVParameter);
        }
    
        public virtual int CSP_REGISTRAVENTA(string iD_TIENDA, string iD_OP, string iD_CLIENTE, string iD_VENDEDOR, Nullable<decimal> rATE, string nO_DOC, string sTATUS, Nullable<decimal> iMPORTE, Nullable<decimal> dESPORCEN, Nullable<decimal> dESCIMP, Nullable<decimal> sUBTOTAL, Nullable<decimal> iVA, Nullable<decimal> iPS, Nullable<decimal> tOTAL, string iD_USUARIO, Nullable<System.DateTime> fECHAOP, Nullable<System.DateTime> hORAOP, Nullable<System.DateTime> fECHAEDIT, string iD_USUARIOEDIT, Nullable<decimal> cOSTOTOTAL, Nullable<decimal> tIPOCAMBIO)
        {
            var iD_TIENDAParameter = iD_TIENDA != null ?
                new ObjectParameter("ID_TIENDA", iD_TIENDA) :
                new ObjectParameter("ID_TIENDA", typeof(string));
    
            var iD_OPParameter = iD_OP != null ?
                new ObjectParameter("ID_OP", iD_OP) :
                new ObjectParameter("ID_OP", typeof(string));
    
            var iD_CLIENTEParameter = iD_CLIENTE != null ?
                new ObjectParameter("ID_CLIENTE", iD_CLIENTE) :
                new ObjectParameter("ID_CLIENTE", typeof(string));
    
            var iD_VENDEDORParameter = iD_VENDEDOR != null ?
                new ObjectParameter("ID_VENDEDOR", iD_VENDEDOR) :
                new ObjectParameter("ID_VENDEDOR", typeof(string));
    
            var rATEParameter = rATE.HasValue ?
                new ObjectParameter("RATE", rATE) :
                new ObjectParameter("RATE", typeof(decimal));
    
            var nO_DOCParameter = nO_DOC != null ?
                new ObjectParameter("NO_DOC", nO_DOC) :
                new ObjectParameter("NO_DOC", typeof(string));
    
            var sTATUSParameter = sTATUS != null ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(string));
    
            var iMPORTEParameter = iMPORTE.HasValue ?
                new ObjectParameter("IMPORTE", iMPORTE) :
                new ObjectParameter("IMPORTE", typeof(decimal));
    
            var dESPORCENParameter = dESPORCEN.HasValue ?
                new ObjectParameter("DESPORCEN", dESPORCEN) :
                new ObjectParameter("DESPORCEN", typeof(decimal));
    
            var dESCIMPParameter = dESCIMP.HasValue ?
                new ObjectParameter("DESCIMP", dESCIMP) :
                new ObjectParameter("DESCIMP", typeof(decimal));
    
            var sUBTOTALParameter = sUBTOTAL.HasValue ?
                new ObjectParameter("SUBTOTAL", sUBTOTAL) :
                new ObjectParameter("SUBTOTAL", typeof(decimal));
    
            var iVAParameter = iVA.HasValue ?
                new ObjectParameter("IVA", iVA) :
                new ObjectParameter("IVA", typeof(decimal));
    
            var iPSParameter = iPS.HasValue ?
                new ObjectParameter("IPS", iPS) :
                new ObjectParameter("IPS", typeof(decimal));
    
            var tOTALParameter = tOTAL.HasValue ?
                new ObjectParameter("TOTAL", tOTAL) :
                new ObjectParameter("TOTAL", typeof(decimal));
    
            var iD_USUARIOParameter = iD_USUARIO != null ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(string));
    
            var fECHAOPParameter = fECHAOP.HasValue ?
                new ObjectParameter("FECHAOP", fECHAOP) :
                new ObjectParameter("FECHAOP", typeof(System.DateTime));
    
            var hORAOPParameter = hORAOP.HasValue ?
                new ObjectParameter("HORAOP", hORAOP) :
                new ObjectParameter("HORAOP", typeof(System.DateTime));
    
            var fECHAEDITParameter = fECHAEDIT.HasValue ?
                new ObjectParameter("FECHAEDIT", fECHAEDIT) :
                new ObjectParameter("FECHAEDIT", typeof(System.DateTime));
    
            var iD_USUARIOEDITParameter = iD_USUARIOEDIT != null ?
                new ObjectParameter("ID_USUARIOEDIT", iD_USUARIOEDIT) :
                new ObjectParameter("ID_USUARIOEDIT", typeof(string));
    
            var cOSTOTOTALParameter = cOSTOTOTAL.HasValue ?
                new ObjectParameter("COSTOTOTAL", cOSTOTOTAL) :
                new ObjectParameter("COSTOTOTAL", typeof(decimal));
    
            var tIPOCAMBIOParameter = tIPOCAMBIO.HasValue ?
                new ObjectParameter("TIPOCAMBIO", tIPOCAMBIO) :
                new ObjectParameter("TIPOCAMBIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_REGISTRAVENTA", iD_TIENDAParameter, iD_OPParameter, iD_CLIENTEParameter, iD_VENDEDORParameter, rATEParameter, nO_DOCParameter, sTATUSParameter, iMPORTEParameter, dESPORCENParameter, dESCIMPParameter, sUBTOTALParameter, iVAParameter, iPSParameter, tOTALParameter, iD_USUARIOParameter, fECHAOPParameter, hORAOPParameter, fECHAEDITParameter, iD_USUARIOEDITParameter, cOSTOTOTALParameter, tIPOCAMBIOParameter);
        }
    
        public virtual int CSP_REGISTRAVENTADET(string iD_OP, string iD_PRODUCTO, string iD_PROVEEDOR, string iD_DEPTO, string iD_FAMILIA, string iD_SUBFAMILIA, Nullable<int> cANT, string dESCRIPCION, Nullable<decimal> pRECIOCONIVA, Nullable<decimal> dESCPORC, Nullable<decimal> dESCIMP, Nullable<decimal> pRECIOVENTA, Nullable<decimal> iMPORTE, Nullable<decimal> pORCIVA, Nullable<decimal> iVA, Nullable<decimal> iPSPOC, Nullable<decimal> iPS, Nullable<decimal> pRECIOSINIVA, Nullable<decimal> dESCIMPSINIVA, Nullable<decimal> pRECIOVENTASINIVA, Nullable<decimal> iMPORTESINIVA, Nullable<decimal> cOSTO, Nullable<decimal> cOSTOIMORTE, Nullable<decimal> dEVUELTOS)
        {
            var iD_OPParameter = iD_OP != null ?
                new ObjectParameter("ID_OP", iD_OP) :
                new ObjectParameter("ID_OP", typeof(string));
    
            var iD_PRODUCTOParameter = iD_PRODUCTO != null ?
                new ObjectParameter("ID_PRODUCTO", iD_PRODUCTO) :
                new ObjectParameter("ID_PRODUCTO", typeof(string));
    
            var iD_PROVEEDORParameter = iD_PROVEEDOR != null ?
                new ObjectParameter("ID_PROVEEDOR", iD_PROVEEDOR) :
                new ObjectParameter("ID_PROVEEDOR", typeof(string));
    
            var iD_DEPTOParameter = iD_DEPTO != null ?
                new ObjectParameter("ID_DEPTO", iD_DEPTO) :
                new ObjectParameter("ID_DEPTO", typeof(string));
    
            var iD_FAMILIAParameter = iD_FAMILIA != null ?
                new ObjectParameter("ID_FAMILIA", iD_FAMILIA) :
                new ObjectParameter("ID_FAMILIA", typeof(string));
    
            var iD_SUBFAMILIAParameter = iD_SUBFAMILIA != null ?
                new ObjectParameter("ID_SUBFAMILIA", iD_SUBFAMILIA) :
                new ObjectParameter("ID_SUBFAMILIA", typeof(string));
    
            var cANTParameter = cANT.HasValue ?
                new ObjectParameter("CANT", cANT) :
                new ObjectParameter("CANT", typeof(int));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var pRECIOCONIVAParameter = pRECIOCONIVA.HasValue ?
                new ObjectParameter("PRECIOCONIVA", pRECIOCONIVA) :
                new ObjectParameter("PRECIOCONIVA", typeof(decimal));
    
            var dESCPORCParameter = dESCPORC.HasValue ?
                new ObjectParameter("DESCPORC", dESCPORC) :
                new ObjectParameter("DESCPORC", typeof(decimal));
    
            var dESCIMPParameter = dESCIMP.HasValue ?
                new ObjectParameter("DESCIMP", dESCIMP) :
                new ObjectParameter("DESCIMP", typeof(decimal));
    
            var pRECIOVENTAParameter = pRECIOVENTA.HasValue ?
                new ObjectParameter("PRECIOVENTA", pRECIOVENTA) :
                new ObjectParameter("PRECIOVENTA", typeof(decimal));
    
            var iMPORTEParameter = iMPORTE.HasValue ?
                new ObjectParameter("IMPORTE", iMPORTE) :
                new ObjectParameter("IMPORTE", typeof(decimal));
    
            var pORCIVAParameter = pORCIVA.HasValue ?
                new ObjectParameter("PORCIVA", pORCIVA) :
                new ObjectParameter("PORCIVA", typeof(decimal));
    
            var iVAParameter = iVA.HasValue ?
                new ObjectParameter("IVA", iVA) :
                new ObjectParameter("IVA", typeof(decimal));
    
            var iPSPOCParameter = iPSPOC.HasValue ?
                new ObjectParameter("IPSPOC", iPSPOC) :
                new ObjectParameter("IPSPOC", typeof(decimal));
    
            var iPSParameter = iPS.HasValue ?
                new ObjectParameter("IPS", iPS) :
                new ObjectParameter("IPS", typeof(decimal));
    
            var pRECIOSINIVAParameter = pRECIOSINIVA.HasValue ?
                new ObjectParameter("PRECIOSINIVA", pRECIOSINIVA) :
                new ObjectParameter("PRECIOSINIVA", typeof(decimal));
    
            var dESCIMPSINIVAParameter = dESCIMPSINIVA.HasValue ?
                new ObjectParameter("DESCIMPSINIVA", dESCIMPSINIVA) :
                new ObjectParameter("DESCIMPSINIVA", typeof(decimal));
    
            var pRECIOVENTASINIVAParameter = pRECIOVENTASINIVA.HasValue ?
                new ObjectParameter("PRECIOVENTASINIVA", pRECIOVENTASINIVA) :
                new ObjectParameter("PRECIOVENTASINIVA", typeof(decimal));
    
            var iMPORTESINIVAParameter = iMPORTESINIVA.HasValue ?
                new ObjectParameter("IMPORTESINIVA", iMPORTESINIVA) :
                new ObjectParameter("IMPORTESINIVA", typeof(decimal));
    
            var cOSTOParameter = cOSTO.HasValue ?
                new ObjectParameter("COSTO", cOSTO) :
                new ObjectParameter("COSTO", typeof(decimal));
    
            var cOSTOIMORTEParameter = cOSTOIMORTE.HasValue ?
                new ObjectParameter("COSTOIMORTE", cOSTOIMORTE) :
                new ObjectParameter("COSTOIMORTE", typeof(decimal));
    
            var dEVUELTOSParameter = dEVUELTOS.HasValue ?
                new ObjectParameter("DEVUELTOS", dEVUELTOS) :
                new ObjectParameter("DEVUELTOS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_REGISTRAVENTADET", iD_OPParameter, iD_PRODUCTOParameter, iD_PROVEEDORParameter, iD_DEPTOParameter, iD_FAMILIAParameter, iD_SUBFAMILIAParameter, cANTParameter, dESCRIPCIONParameter, pRECIOCONIVAParameter, dESCPORCParameter, dESCIMPParameter, pRECIOVENTAParameter, iMPORTEParameter, pORCIVAParameter, iVAParameter, iPSPOCParameter, iPSParameter, pRECIOSINIVAParameter, dESCIMPSINIVAParameter, pRECIOVENTASINIVAParameter, iMPORTESINIVAParameter, cOSTOParameter, cOSTOIMORTEParameter, dEVUELTOSParameter);
        }
    
        public virtual ObjectResult<CSP_REPORTEVENTAS_Result> CSP_REPORTEVENTAS(Nullable<System.DateTime> fECHAINI, Nullable<System.DateTime> fECHAFIN, string iD_USUARIO, string iD_VENDEDOR, string iD_PRODUCTO, string iD_PROVEEDOR, string iD_DEPTO, string iD_FAMILIA, string iD_SUBFAMILIA, string tIPOPRODUCTO, Nullable<decimal> cOSTO, Nullable<bool> mAYOR, string cRITERIOGRUPO)
        {
            var fECHAINIParameter = fECHAINI.HasValue ?
                new ObjectParameter("FECHAINI", fECHAINI) :
                new ObjectParameter("FECHAINI", typeof(System.DateTime));
    
            var fECHAFINParameter = fECHAFIN.HasValue ?
                new ObjectParameter("FECHAFIN", fECHAFIN) :
                new ObjectParameter("FECHAFIN", typeof(System.DateTime));
    
            var iD_USUARIOParameter = iD_USUARIO != null ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(string));
    
            var iD_VENDEDORParameter = iD_VENDEDOR != null ?
                new ObjectParameter("ID_VENDEDOR", iD_VENDEDOR) :
                new ObjectParameter("ID_VENDEDOR", typeof(string));
    
            var iD_PRODUCTOParameter = iD_PRODUCTO != null ?
                new ObjectParameter("ID_PRODUCTO", iD_PRODUCTO) :
                new ObjectParameter("ID_PRODUCTO", typeof(string));
    
            var iD_PROVEEDORParameter = iD_PROVEEDOR != null ?
                new ObjectParameter("ID_PROVEEDOR", iD_PROVEEDOR) :
                new ObjectParameter("ID_PROVEEDOR", typeof(string));
    
            var iD_DEPTOParameter = iD_DEPTO != null ?
                new ObjectParameter("ID_DEPTO", iD_DEPTO) :
                new ObjectParameter("ID_DEPTO", typeof(string));
    
            var iD_FAMILIAParameter = iD_FAMILIA != null ?
                new ObjectParameter("ID_FAMILIA", iD_FAMILIA) :
                new ObjectParameter("ID_FAMILIA", typeof(string));
    
            var iD_SUBFAMILIAParameter = iD_SUBFAMILIA != null ?
                new ObjectParameter("ID_SUBFAMILIA", iD_SUBFAMILIA) :
                new ObjectParameter("ID_SUBFAMILIA", typeof(string));
    
            var tIPOPRODUCTOParameter = tIPOPRODUCTO != null ?
                new ObjectParameter("TIPOPRODUCTO", tIPOPRODUCTO) :
                new ObjectParameter("TIPOPRODUCTO", typeof(string));
    
            var cOSTOParameter = cOSTO.HasValue ?
                new ObjectParameter("COSTO", cOSTO) :
                new ObjectParameter("COSTO", typeof(decimal));
    
            var mAYORParameter = mAYOR.HasValue ?
                new ObjectParameter("MAYOR", mAYOR) :
                new ObjectParameter("MAYOR", typeof(bool));
    
            var cRITERIOGRUPOParameter = cRITERIOGRUPO != null ?
                new ObjectParameter("CRITERIOGRUPO", cRITERIOGRUPO) :
                new ObjectParameter("CRITERIOGRUPO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_REPORTEVENTAS_Result>("CSP_REPORTEVENTAS", fECHAINIParameter, fECHAFINParameter, iD_USUARIOParameter, iD_VENDEDORParameter, iD_PRODUCTOParameter, iD_PROVEEDORParameter, iD_DEPTOParameter, iD_FAMILIAParameter, iD_SUBFAMILIAParameter, tIPOPRODUCTOParameter, cOSTOParameter, mAYORParameter, cRITERIOGRUPOParameter);
        }
    
        public virtual int dt_addtosourcecontrol(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_addtosourcecontrol_u(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_addtosourcecontrol_u", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_adduserobject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject");
        }
    
        public virtual int dt_adduserobject_vcs(string vchProperty)
        {
            var vchPropertyParameter = vchProperty != null ?
                new ObjectParameter("vchProperty", vchProperty) :
                new ObjectParameter("vchProperty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject_vcs", vchPropertyParameter);
        }
    
        public virtual int dt_checkinobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkinobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkoutobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_checkoutobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_displayoaerror(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_displayoaerror_u(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror_u", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_droppropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_droppropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual int dt_dropuserobjectbyid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_dropuserobjectbyid", idParameter);
        }
    
        public virtual int dt_generateansiname(ObjectParameter name)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_generateansiname", name);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop(string property, string value)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop", propertyParameter, valueParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop_u(string property, string uvalue)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop_u", propertyParameter, uvalueParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_Result> dt_getpropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_Result>("dt_getpropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_u_Result> dt_getpropertiesbyid_u(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_u_Result>("dt_getpropertiesbyid_u", idParameter, propertyParameter);
        }
    
        public virtual int dt_getpropertiesbyid_vcs(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_getpropertiesbyid_vcs_u(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs_u", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_isundersourcecontrol(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_isundersourcecontrol_u(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol_u", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_removefromsourcecontrol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_removefromsourcecontrol");
        }
    
        public virtual int dt_setpropertybyid(Nullable<int> id, string property, string value, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid", idParameter, propertyParameter, valueParameter, lvalueParameter);
        }
    
        public virtual int dt_setpropertybyid_u(Nullable<int> id, string property, string uvalue, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid_u", idParameter, propertyParameter, uvalueParameter, lvalueParameter);
        }
    
        public virtual int dt_validateloginparams(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_validateloginparams_u(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams_u", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_vcsenabled()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_vcsenabled");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp006()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp006");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp007()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp007");
        }
    
        public virtual int dt_whocheckedout(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_whocheckedout_u(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_whocheckedout_u", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    }
}
